In [2]:
from pathlib import Path
import pandas as pd
import os

In [3]:
# Get the current working directory (which should be the Notebooks folder)
current_directory = Path(os.getcwd())

# Define the project root directory by navigating up one level from the Notebooks folder
project_root = current_directory.parent

# Construct the path to the CSV file in the dataset folder
cutoff_file_path = project_root / 'dataset' / 'cutoff.csv'

In [4]:
df = pd.read_csv(cutoff_file_path)

In [5]:
df

,InstituteId,InstituteName,BranchCode,1G,1K,1R,2AG,2AK,2AR,2BG,...,3BR,GM,GMK,GMR,SCG,SCK,SCR,STG,STK,STR
0,E001,University of Visvesvaraya College of Engineer...,AI,10087.0,20801.0,NaN,9302.0,NaN,10041.0,12213.0,...,NaN,6935.0,7979.0,8653.0,26148.0,NaN,33645.0,24190.0,NaN,33807.0
1,E001,University of Visvesvaraya College of Engineer...,CE,126281.0,NaN,140951.0,99176.0,NaN,110030.0,95076.0,...,95251.0,74111.0,84671.0,86716.0,105351.0,132307.0,186680.0,109874.0,NaN,129504.0
2,E001,University of Visvesvaraya College of Engineer...,CS,5809.0,NaN,NaN,5835.0,7296.0,6519.0,7166.0,...,5708.0,4344.0,6701.0,5402.0,20990.0,28206.0,29187.0,15475.0,16438.0,20958.0
3,E001,University of Visvesvaraya College of Engineer...,EC,15177.0,NaN,18548.0,14878.0,15407.0,16522.0,21600.0,...,14664.0,9878.0,14864.0,11936.0,33658.0,46591.0,47113.0,37482.0,NaN,52570.0
4,E001,University of Visvesvaraya College of Engineer...,EE,41399.0,NaN,55688.0,37226.0,39400.0,43302.0,59169.0,...,34904.0,23821.0,32204.0,31736.0,69595.0,73849.0,74966.0,72997.0,NaN,78257.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,196309.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1465,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,182360.0,NaN,NaN,196735.0,NaN,NaN,NaN,NaN,NaN
1466,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,200270.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1467,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,196205.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1468,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,178340.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# List of columns to exclude
columns_to_exclude = ['InstituteId', 'InstituteName', 'BranchCode']

# Create a variable with columns excluded
cut_off_data_columns = [col for col in df.columns if col not in columns_to_exclude]

In [7]:
cut_off_data_columns

['1G',
 '1K',
 '1R',
 '2AG',
 '2AK',
 '2AR',
 '2BG',
 '2BK',
 '2BR',
 '3AG',
 '3AK',
 '3AR',
 '3BG',
 '3BK',
 '3BR',
 'GM',
 'GMK',
 'GMR',
 'SCG',
 'SCK',
 'SCR',
 'STG',
 'STK',
 'STR']

In [8]:
df

,InstituteId,InstituteName,BranchCode,1G,1K,1R,2AG,2AK,2AR,2BG,...,3BR,GM,GMK,GMR,SCG,SCK,SCR,STG,STK,STR
0,E001,University of Visvesvaraya College of Engineer...,AI,10087.0,20801.0,NaN,9302.0,NaN,10041.0,12213.0,...,NaN,6935.0,7979.0,8653.0,26148.0,NaN,33645.0,24190.0,NaN,33807.0
1,E001,University of Visvesvaraya College of Engineer...,CE,126281.0,NaN,140951.0,99176.0,NaN,110030.0,95076.0,...,95251.0,74111.0,84671.0,86716.0,105351.0,132307.0,186680.0,109874.0,NaN,129504.0
2,E001,University of Visvesvaraya College of Engineer...,CS,5809.0,NaN,NaN,5835.0,7296.0,6519.0,7166.0,...,5708.0,4344.0,6701.0,5402.0,20990.0,28206.0,29187.0,15475.0,16438.0,20958.0
3,E001,University of Visvesvaraya College of Engineer...,EC,15177.0,NaN,18548.0,14878.0,15407.0,16522.0,21600.0,...,14664.0,9878.0,14864.0,11936.0,33658.0,46591.0,47113.0,37482.0,NaN,52570.0
4,E001,University of Visvesvaraya College of Engineer...,EE,41399.0,NaN,55688.0,37226.0,39400.0,43302.0,59169.0,...,34904.0,23821.0,32204.0,31736.0,69595.0,73849.0,74966.0,72997.0,NaN,78257.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,196309.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1465,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,182360.0,NaN,NaN,196735.0,NaN,NaN,NaN,NaN,NaN
1466,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,200270.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1467,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,196205.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1468,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,178340.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.dtypes

InstituteId       object
InstituteName     object
BranchCode        object
1G               float64
1K               float64
1R               float64
2AG              float64
2AK              float64
2AR              float64
2BG              float64
2BK              float64
2BR              float64
3AG              float64
3AK              float64
3AR              float64
3BG              float64
3BK              float64
3BR              float64
GM               float64
GMK              float64
GMR              float64
SCG              float64
SCK              float64
SCR              float64
STG              float64
STK              float64
STR              float64
dtype: object

In [10]:
# Convert float64 columns to integers and replace NaN with empty strings
for column in df.select_dtypes(include='float64').columns:
    df[column] = df[column].fillna(0).astype(int)

In [11]:
df

,InstituteId,InstituteName,BranchCode,1G,1K,1R,2AG,2AK,2AR,2BG,...,3BR,GM,GMK,GMR,SCG,SCK,SCR,STG,STK,STR
0,E001,University of Visvesvaraya College of Engineer...,AI,10087,20801,0,9302,0,10041,12213,...,0,6935,7979,8653,26148,0,33645,24190,0,33807
1,E001,University of Visvesvaraya College of Engineer...,CE,126281,0,140951,99176,0,110030,95076,...,95251,74111,84671,86716,105351,132307,186680,109874,0,129504
2,E001,University of Visvesvaraya College of Engineer...,CS,5809,0,0,5835,7296,6519,7166,...,5708,4344,6701,5402,20990,28206,29187,15475,16438,20958
3,E001,University of Visvesvaraya College of Engineer...,EC,15177,0,18548,14878,15407,16522,21600,...,14664,9878,14864,11936,33658,46591,47113,37482,0,52570
4,E001,University of Visvesvaraya College of Engineer...,EE,41399,0,55688,37226,39400,43302,59169,...,34904,23821,32204,31736,69595,73849,74966,72997,0,78257
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LF,0,0,0,0,0,0,0,...,0,196309,0,0,0,0,0,0,0,0
1465,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LG,0,0,0,0,0,0,0,...,0,182360,0,0,196735,0,0,0,0,0
1466,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LH,0,0,0,0,0,0,0,...,0,200270,0,0,0,0,0,0,0,0
1467,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LJ,0,0,0,0,0,0,0,...,0,196205,0,0,0,0,0,0,0,0
1468,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LK,0,0,0,0,0,0,0,...,0,178340,0,0,0,0,0,0,0,0

In [12]:
df.shape

(1469, 27)

In [13]:
# Construct the path to the CSV file in the dataset folder
cleaned_cutoff_file_path = project_root / 'dataset' / 'cleaned_cutoff.csv'

df.to_csv(cleaned_cutoff_file_path)

In [14]:
df

,InstituteId,InstituteName,BranchCode,1G,1K,1R,2AG,2AK,2AR,2BG,...,3BR,GM,GMK,GMR,SCG,SCK,SCR,STG,STK,STR
0,E001,University of Visvesvaraya College of Engineer...,AI,10087,20801,0,9302,0,10041,12213,...,0,6935,7979,8653,26148,0,33645,24190,0,33807
1,E001,University of Visvesvaraya College of Engineer...,CE,126281,0,140951,99176,0,110030,95076,...,95251,74111,84671,86716,105351,132307,186680,109874,0,129504
2,E001,University of Visvesvaraya College of Engineer...,CS,5809,0,0,5835,7296,6519,7166,...,5708,4344,6701,5402,20990,28206,29187,15475,16438,20958
3,E001,University of Visvesvaraya College of Engineer...,EC,15177,0,18548,14878,15407,16522,21600,...,14664,9878,14864,11936,33658,46591,47113,37482,0,52570
4,E001,University of Visvesvaraya College of Engineer...,EE,41399,0,55688,37226,39400,43302,59169,...,34904,23821,32204,31736,69595,73849,74966,72997,0,78257
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LF,0,0,0,0,0,0,0,...,0,196309,0,0,0,0,0,0,0,0
1465,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LG,0,0,0,0,0,0,0,...,0,182360,0,0,196735,0,0,0,0,0
1466,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LH,0,0,0,0,0,0,0,...,0,200270,0,0,0,0,0,0,0,0
1467,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LJ,0,0,0,0,0,0,0,...,0,196205,0,0,0,0,0,0,0,0
1468,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LK,0,0,0,0,0,0,0,...,0,178340,0,0,0,0,0,0,0,0

In [15]:
course_data_file_path = project_root / 'dataset' / 'courses.csv'
course_df = pd.read_csv(course_data_file_path)

In [16]:
course_df

    CourseCode                                    CourseName
0           AD      Artificial Intelligence And Data Science
1           AE                      Aeronautical Engineering
2           AI  Artificial Intelligence and Machine Learning
3           AM           B TECH IN COMP SCI & ENGG (AI & ML)
4           AR                                  Architecture
..         ...                                           ...
133         TX                            Textile Technology
134         UP                                      Planning
135         UR                                      Planning
136         ZC                              COMPUTER SCIENCE
137         mn                            Mining Engineering

[138 rows x 2 columns]

In [17]:
# Perform a left join between df and courses_df on 'BranchCode' and 'Code'
merged_df = pd.merge(df, course_df, how='left', left_on='BranchCode', right_on='CourseCode')

# Rename the 'course name' column to 'branchname'
merged_df.rename(columns={'course name': 'branchname'}, inplace=True)

# Drop the duplicated 'Code' column
merged_df.drop('CourseCode', axis=1, inplace=True)

In [18]:
df2  = merged_df

In [19]:
df2

,InstituteId,InstituteName,BranchCode,1G,1K,1R,2AG,2AK,2AR,2BG,...,GM,GMK,GMR,SCG,SCK,SCR,STG,STK,STR,CourseName
0,E001,University of Visvesvaraya College of Engineer...,AI,10087,20801,0,9302,0,10041,12213,...,6935,7979,8653,26148,0,33645,24190,0,33807,Artificial Intelligence and Machine Learning
1,E001,University of Visvesvaraya College of Engineer...,CE,126281,0,140951,99176,0,110030,95076,...,74111,84671,86716,105351,132307,186680,109874,0,129504,Civil Engineering
2,E001,University of Visvesvaraya College of Engineer...,CS,5809,0,0,5835,7296,6519,7166,...,4344,6701,5402,20990,28206,29187,15475,16438,20958,Computers Science And Engineering
3,E001,University of Visvesvaraya College of Engineer...,EC,15177,0,18548,14878,15407,16522,21600,...,9878,14864,11936,33658,46591,47113,37482,0,52570,Electronics and Communication Engineering
4,E001,University of Visvesvaraya College of Engineer...,EE,41399,0,55688,37226,39400,43302,59169,...,23821,32204,31736,69595,73849,74966,72997,0,78257,Electrical And Electronics Engineering
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LF,0,0,0,0,0,0,0,...,196309,0,0,0,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (CLOUD
1465,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LG,0,0,0,0,0,0,0,...,182360,0,0,196735,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (CYBER SECURITY)
1466,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LH,0,0,0,0,0,0,0,...,200270,0,0,0,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (INFORMATION)
1467,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LJ,0,0,0,0,0,0,0,...,196205,0,0,0,0,0,0,0,0,BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYS...
1468,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LK,0,0,0,0,0,0,0,...,178340,0,0,0,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS)

In [20]:
college_data_file_path = project_root / 'dynamic_data' / 'college_data.csv'
df2[[ 'InstituteId', 'InstituteName']].drop_duplicates(subset='InstituteId', keep='first')
df2.reset_index(drop=True, inplace=True)

In [21]:
df2

,InstituteId,InstituteName,BranchCode,1G,1K,1R,2AG,2AK,2AR,2BG,...,GM,GMK,GMR,SCG,SCK,SCR,STG,STK,STR,CourseName
0,E001,University of Visvesvaraya College of Engineer...,AI,10087,20801,0,9302,0,10041,12213,...,6935,7979,8653,26148,0,33645,24190,0,33807,Artificial Intelligence and Machine Learning
1,E001,University of Visvesvaraya College of Engineer...,CE,126281,0,140951,99176,0,110030,95076,...,74111,84671,86716,105351,132307,186680,109874,0,129504,Civil Engineering
2,E001,University of Visvesvaraya College of Engineer...,CS,5809,0,0,5835,7296,6519,7166,...,4344,6701,5402,20990,28206,29187,15475,16438,20958,Computers Science And Engineering
3,E001,University of Visvesvaraya College of Engineer...,EC,15177,0,18548,14878,15407,16522,21600,...,9878,14864,11936,33658,46591,47113,37482,0,52570,Electronics and Communication Engineering
4,E001,University of Visvesvaraya College of Engineer...,EE,41399,0,55688,37226,39400,43302,59169,...,23821,32204,31736,69595,73849,74966,72997,0,78257,Electrical And Electronics Engineering
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LF,0,0,0,0,0,0,0,...,196309,0,0,0,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (CLOUD
1465,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LG,0,0,0,0,0,0,0,...,182360,0,0,196735,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (CYBER SECURITY)
1466,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LH,0,0,0,0,0,0,0,...,200270,0,0,0,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (INFORMATION)
1467,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LJ,0,0,0,0,0,0,0,...,196205,0,0,0,0,0,0,0,0,BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYS...
1468,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LK,0,0,0,0,0,0,0,...,178340,0,0,0,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS)

In [22]:
df3 = df2[[ 'InstituteId', 'InstituteName']].drop_duplicates(subset='InstituteId', keep='first')

In [23]:
df3.reset_index(drop=True, inplace=True)

In [24]:
df3.to_csv(college_data_file_path)

In [25]:
df2

,InstituteId,InstituteName,BranchCode,1G,1K,1R,2AG,2AK,2AR,2BG,...,GM,GMK,GMR,SCG,SCK,SCR,STG,STK,STR,CourseName
0,E001,University of Visvesvaraya College of Engineer...,AI,10087,20801,0,9302,0,10041,12213,...,6935,7979,8653,26148,0,33645,24190,0,33807,Artificial Intelligence and Machine Learning
1,E001,University of Visvesvaraya College of Engineer...,CE,126281,0,140951,99176,0,110030,95076,...,74111,84671,86716,105351,132307,186680,109874,0,129504,Civil Engineering
2,E001,University of Visvesvaraya College of Engineer...,CS,5809,0,0,5835,7296,6519,7166,...,4344,6701,5402,20990,28206,29187,15475,16438,20958,Computers Science And Engineering
3,E001,University of Visvesvaraya College of Engineer...,EC,15177,0,18548,14878,15407,16522,21600,...,9878,14864,11936,33658,46591,47113,37482,0,52570,Electronics and Communication Engineering
4,E001,University of Visvesvaraya College of Engineer...,EE,41399,0,55688,37226,39400,43302,59169,...,23821,32204,31736,69595,73849,74966,72997,0,78257,Electrical And Electronics Engineering
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LF,0,0,0,0,0,0,0,...,196309,0,0,0,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (CLOUD
1465,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LG,0,0,0,0,0,0,0,...,182360,0,0,196735,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (CYBER SECURITY)
1466,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LH,0,0,0,0,0,0,0,...,200270,0,0,0,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (INFORMATION)
1467,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LJ,0,0,0,0,0,0,0,...,196205,0,0,0,0,0,0,0,0,BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYS...
1468,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LK,0,0,0,0,0,0,0,...,178340,0,0,0,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS)

In [26]:
grab_location_file_path = project_root / 'dynamic_data' / 'CET_Database_Final2020.csv'
loc_df= pd.read_csv(grab_location_file_path)

In [27]:
loc_df = loc_df[['CETCode', 'College', 'Location']]

In [28]:
loc_df

,CETCode,College,Location
0,NaN,NaN,NaN
1,E001,University Visveswariah College of Engineering,"KR Circle, Bengaluru"
2,E001,University Visveswariah College of Engineering,"KR Circle, Bengaluru"
3,E001,University Visveswariah College of Engineering,"KR Circle, Bengaluru"
4,E001,University Visveswariah College of Engineering,"KR Circle, Bengaluru"
...,...,...,...
1726,NaN,NaN,NaN
1727,NaN,NaN,NaN
1728,NaN,NaN,NaN
1729,NaN,NaN,NaN
1730,NaN,NaN,NaN

In [29]:
# Drop duplicate rows based on the 'CETCode' column, keeping the first occurrence
unique_loc_df = loc_df.drop_duplicates(subset='CETCode', keep='first')

In [30]:
unique_loc_df

,CETCode,College,Location
0,NaN,NaN,NaN
1,E001,University Visveswariah College of Engineering,"KR Circle, Bengaluru"
8,E002,SKSJT Institute of Engineering,"Sampangi Rama Nagar, Bengaluru"
14,E003,BMS College of Engineering (Aided),"Basavanagudi, Bengaluru"
20,E004,Dr. Ambedkar Institute Of Technology (Aided),"Near Gnana Bharathi, Bengaluru"
...,...,...,...
1410,E273,Government Engineering College,"Viprasainagar, Gangavathi, Koppal"
1416,E274,Government Engineering College,"Moselehosahalli,Hassan"
1422,E275,RV Institute of Technology and Management,"JP nagar,Bengaluru"
1427,E278,Visvesvaraya Technological University (VTU),"Muddenahalli,Chickkaballapur"
1429,E279,Visvesvaraya Technological University (VTU),Belgaum

In [31]:
# Reset the index of the resulting DataFrame
unique_loc_df.reset_index(drop=True, inplace=True)

In [32]:
unique_loc_df

,CETCode,College,Location
0,NaN,NaN,NaN
1,E001,University Visveswariah College of Engineering,"KR Circle, Bengaluru"
2,E002,SKSJT Institute of Engineering,"Sampangi Rama Nagar, Bengaluru"
3,E003,BMS College of Engineering (Aided),"Basavanagudi, Bengaluru"
4,E004,Dr. Ambedkar Institute Of Technology (Aided),"Near Gnana Bharathi, Bengaluru"
...,...,...,...
202,E273,Government Engineering College,"Viprasainagar, Gangavathi, Koppal"
203,E274,Government Engineering College,"Moselehosahalli,Hassan"
204,E275,RV Institute of Technology and Management,"JP nagar,Bengaluru"
205,E278,Visvesvaraya Technological University (VTU),"Muddenahalli,Chickkaballapur"
206,E279,Visvesvaraya Technological University (VTU),Belgaum

In [33]:
unique_loc_df = unique_loc_df.dropna()

In [34]:
location_data_file_path = project_root / 'dynamic_data' / 'college_location_data.csv'
unique_loc_df.to_csv(location_data_file_path)

In [35]:
unique_loc_df[ unique_loc_df['CETCode'] == 'E279']

    CETCode                                      College Location
206    E279  Visvesvaraya Technological University (VTU)  Belgaum

In [36]:
college_data = pd.read_csv( project_root / 'dynamic_data' / 'college_data.csv')

In [37]:
college_data['Institution'] = college_data['InstituteName'] +' [' + college_data['InstituteId'] + ']'

In [38]:
college_data = college_data.sort_values(by = 'InstituteName', ascending = True)

In [39]:
college_data.reset_index(drop = True, inplace = True)

In [40]:
college_data.drop(columns=['Unnamed: 0'], inplace=True)

In [41]:
college_data.to_csv( project_root / 'dropdowndata' / 'college_data.csv')

In [42]:
df2

,InstituteId,InstituteName,BranchCode,1G,1K,1R,2AG,2AK,2AR,2BG,...,GM,GMK,GMR,SCG,SCK,SCR,STG,STK,STR,CourseName
0,E001,University of Visvesvaraya College of Engineer...,AI,10087,20801,0,9302,0,10041,12213,...,6935,7979,8653,26148,0,33645,24190,0,33807,Artificial Intelligence and Machine Learning
1,E001,University of Visvesvaraya College of Engineer...,CE,126281,0,140951,99176,0,110030,95076,...,74111,84671,86716,105351,132307,186680,109874,0,129504,Civil Engineering
2,E001,University of Visvesvaraya College of Engineer...,CS,5809,0,0,5835,7296,6519,7166,...,4344,6701,5402,20990,28206,29187,15475,16438,20958,Computers Science And Engineering
3,E001,University of Visvesvaraya College of Engineer...,EC,15177,0,18548,14878,15407,16522,21600,...,9878,14864,11936,33658,46591,47113,37482,0,52570,Electronics and Communication Engineering
4,E001,University of Visvesvaraya College of Engineer...,EE,41399,0,55688,37226,39400,43302,59169,...,23821,32204,31736,69595,73849,74966,72997,0,78257,Electrical And Electronics Engineering
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LF,0,0,0,0,0,0,0,...,196309,0,0,0,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (CLOUD
1465,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LG,0,0,0,0,0,0,0,...,182360,0,0,196735,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (CYBER SECURITY)
1466,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LH,0,0,0,0,0,0,0,...,200270,0,0,0,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (INFORMATION)
1467,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LJ,0,0,0,0,0,0,0,...,196205,0,0,0,0,0,0,0,0,BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYS...
1468,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LK,0,0,0,0,0,0,0,...,178340,0,0,0,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS)

In [43]:
df4 = df2

In [44]:
df4

,InstituteId,InstituteName,BranchCode,1G,1K,1R,2AG,2AK,2AR,2BG,...,GM,GMK,GMR,SCG,SCK,SCR,STG,STK,STR,CourseName
0,E001,University of Visvesvaraya College of Engineer...,AI,10087,20801,0,9302,0,10041,12213,...,6935,7979,8653,26148,0,33645,24190,0,33807,Artificial Intelligence and Machine Learning
1,E001,University of Visvesvaraya College of Engineer...,CE,126281,0,140951,99176,0,110030,95076,...,74111,84671,86716,105351,132307,186680,109874,0,129504,Civil Engineering
2,E001,University of Visvesvaraya College of Engineer...,CS,5809,0,0,5835,7296,6519,7166,...,4344,6701,5402,20990,28206,29187,15475,16438,20958,Computers Science And Engineering
3,E001,University of Visvesvaraya College of Engineer...,EC,15177,0,18548,14878,15407,16522,21600,...,9878,14864,11936,33658,46591,47113,37482,0,52570,Electronics and Communication Engineering
4,E001,University of Visvesvaraya College of Engineer...,EE,41399,0,55688,37226,39400,43302,59169,...,23821,32204,31736,69595,73849,74966,72997,0,78257,Electrical And Electronics Engineering
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LF,0,0,0,0,0,0,0,...,196309,0,0,0,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (CLOUD
1465,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LG,0,0,0,0,0,0,0,...,182360,0,0,196735,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (CYBER SECURITY)
1466,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LH,0,0,0,0,0,0,0,...,200270,0,0,0,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (INFORMATION)
1467,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LJ,0,0,0,0,0,0,0,...,196205,0,0,0,0,0,0,0,0,BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYS...
1468,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LK,0,0,0,0,0,0,0,...,178340,0,0,0,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS)

In [45]:
df4['BranchCode'].unique()

array(['AI', 'CE', 'CS', 'EC', 'EE', 'IE', 'ME', 'ST', 'TX', 'IM', 'EI',
       'ET', 'BT', 'CH', 'CY', 'DS', 'SE', 'AD', 'CA', 'MD', 'AE', 'AU',
       'CB', 'CD', 'IC', 'RI', 'EV', 'AM', 'BB', 'BJ', 'BO', 'BW', 'DB',
       'EB', 'OT', 'TC', 'CK', 'mn', 'BM', 'EN', 'IP', 'PT', 'EA', 'CF',
       'CO', 'CT', 'CR', 'MT', 'RA', 'CC', 'ES', 'ZC', 'BK', 'BP', 'RO',
       'MR', 'DC', 'MM', 'MK', 'IO', 'SA', 'BH', 'BL', 'CW', 'DG', 'BA',
       'BG', 'BU', 'CL', 'CN', 'CU', 'DD', 'DF', 'DK', 'AT', 'DA', 'DJ',
       'BN', 'BQ', 'BV', 'BX', 'BY', 'BZ', 'CM', 'CQ', 'CX', 'CZ', 'DE',
       'DM', 'DN', 'DH', 'UP', 'BR', 'CV', 'BF', 'DI', 'DL', 'LD', 'LE',
       'LF', 'LG', 'LH', 'LJ', 'LK'], dtype=object)

In [46]:
df4['course'] = df4['CourseName'] + ' ['+ df4['BranchCode'] + ']'

In [47]:
# Convert 'course' column to strings to handle NaN values
df4['course'] = df4['course'].astype(str)

# Select unique courses and sort alphabetically
unique_courses = sorted(df4['course'].unique())

# Create a new DataFrame with unique courses
unique_courses_df = pd.DataFrame(unique_courses, columns=['Unique Courses'])

# Display the new DataFrame
print(unique_courses_df)

                                        Unique Courses
0     BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYS...
1                          Aero Space Engineering [SE]
2                        Aeronautical Engineering [AE]
3                         Agriculture Engineering [EA]
4        Artificial Intelligence And Data Science [AD]
..                                                 ...
99                        Robotics and Automation [RA]
100                               Silk Technology [ST]
101                                Smart Agritech [SA]
102                 Telecommunication Engineering [TC]
103                            Textile Technology [TX]

[104 rows x 1 columns]

In [48]:
unique_courses_df.dropna().to_csv(project_root / 'dropdowndata' / 'course_data.csv')

In [49]:
college =  college_data

In [50]:
college

,InstituteId,InstituteName,Institution
0,E254,A J Institute Of Engineering And Technology ...,A J Institute Of Engineering And Technology ...
1,E186,"ACS College of Engineering Kengeri Hobli,Ban...","ACS College of Engineering Kengeri Hobli,Ban..."
2,E297,ADITYA COLLEGE OF ENGINEERING AND TECHNOLOGY ...,ADITYA COLLEGE OF ENGINEERING AND TECHNOLOGY ...
3,E199,"AGM Rural Engineering College Hubli, Darward...","AGM Rural Engineering College Hubli, Darward..."
4,E300,AKASH INTITUTE OF ENGINEERING AND TECHNOLOGY ...,AKASH INTITUTE OF ENGINEERING AND TECHNOLOGY ...
...,...,...,...
214,E289,Visvesvaraya Technological University - Regio...,Visvesvaraya Technological University - Regio...
215,E121,Vivekananada College of Engineering Technolog...,Vivekananada College of Engineering Technolog...
216,E087,Vivekananada Institute of Technology Bangalore,Vivekananada Institute of Technology Bangalo...
217,E165,"Yenepoya Institute of Technology Thodar,Mood...","Yenepoya Institute of Technology Thodar,Mood..."
218,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...

In [51]:
college.drop(columns=['InstituteName', 'InstituteId'], inplace=True)

In [52]:
college

                                           Institution
0     A J Institute Of Engineering And Technology  ...
1     ACS College of Engineering  Kengeri Hobli,Ban...
2     ADITYA COLLEGE OF ENGINEERING AND TECHNOLOGY ...
3     AGM Rural Engineering College  Hubli, Darward...
4     AKASH INTITUTE OF ENGINEERING AND TECHNOLOGY ...
..                                                 ...
214   Visvesvaraya Technological University - Regio...
215   Vivekananada College of Engineering Technolog...
216   Vivekananada Institute of Technology  Bangalo...
217   Yenepoya Institute of Technology  Thodar,Mood...
218  University of Visvesvaraya College of Engineer...

[219 rows x 1 columns]

In [53]:
df4

,InstituteId,InstituteName,BranchCode,1G,1K,1R,2AG,2AK,2AR,2BG,...,GMK,GMR,SCG,SCK,SCR,STG,STK,STR,CourseName,course
0,E001,University of Visvesvaraya College of Engineer...,AI,10087,20801,0,9302,0,10041,12213,...,7979,8653,26148,0,33645,24190,0,33807,Artificial Intelligence and Machine Learning,Artificial Intelligence and Machine Learning [AI]
1,E001,University of Visvesvaraya College of Engineer...,CE,126281,0,140951,99176,0,110030,95076,...,84671,86716,105351,132307,186680,109874,0,129504,Civil Engineering,Civil Engineering [CE]
2,E001,University of Visvesvaraya College of Engineer...,CS,5809,0,0,5835,7296,6519,7166,...,6701,5402,20990,28206,29187,15475,16438,20958,Computers Science And Engineering,Computers Science And Engineering [CS]
3,E001,University of Visvesvaraya College of Engineer...,EC,15177,0,18548,14878,15407,16522,21600,...,14864,11936,33658,46591,47113,37482,0,52570,Electronics and Communication Engineering,Electronics and Communication Engineering [EC]
4,E001,University of Visvesvaraya College of Engineer...,EE,41399,0,55688,37226,39400,43302,59169,...,32204,31736,69595,73849,74966,72997,0,78257,Electrical And Electronics Engineering,Electrical And Electronics Engineering [EE]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LF,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (CLOUD,B TECH IN COMPUTER SCIENCE (CLOUD [LF]
1465,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LG,0,0,0,0,0,0,0,...,0,0,196735,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (CYBER SECURITY),B TECH IN COMPUTER SCIENCE (CYBER SECURITY) [LG]
1466,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LH,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (INFORMATION),B TECH IN COMPUTER SCIENCE (INFORMATION) [LH]
1467,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LJ,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYS...,BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYS...
1468,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LK,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS),B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS...

In [54]:
college_data

                                           Institution
0     A J Institute Of Engineering And Technology  ...
1     ACS College of Engineering  Kengeri Hobli,Ban...
2     ADITYA COLLEGE OF ENGINEERING AND TECHNOLOGY ...
3     AGM Rural Engineering College  Hubli, Darward...
4     AKASH INTITUTE OF ENGINEERING AND TECHNOLOGY ...
..                                                 ...
214   Visvesvaraya Technological University - Regio...
215   Vivekananada College of Engineering Technolog...
216   Vivekananada Institute of Technology  Bangalo...
217   Yenepoya Institute of Technology  Thodar,Mood...
218  University of Visvesvaraya College of Engineer...

[219 rows x 1 columns]

In [55]:
college_details = pd.read_csv( project_root / 'dynamic_data' / 'college_data.csv')

In [56]:
college_details

     Unnamed: 0 InstituteId                                      InstituteName
0             0        E001  University of Visvesvaraya College of Engineer...
1             1        E002     S K S J T Institute of Engineering.  Bangalore
2             2        E003   B M S College of Engineering  Basavanagudi,Ba...
3             3        E004    Dr. Ambedkar Institute Of Technology  Bangalore
4             4        E005            R. V. College of Engineering  Bangalore
..          ...         ...                                                ...
214         214        E299   Ghousia Institute of Technology for Women, Ba...
215         215        E300   AKASH INTITUTE OF ENGINEERING AND TECHNOLOGY ...
216         216        E301                      KISHKINDA UNIVERSITY  BELLARI
217         217        E302           AMITY UNIVERSITY  DEVANAHALLI ,BANAGLORE
218         218        E303           G M UNIVERSITY  KARUR VILLAGE, DAVANGERE

[219 rows x 3 columns]

In [57]:
college_details['Institution'] = college_details['InstituteName'] +' [' + college_details['InstituteId'] + ']'

In [58]:
college_details

,Unnamed: 0,InstituteId,InstituteName,Institution
0,0,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...
1,1,E002,S K S J T Institute of Engineering. Bangalore,S K S J T Institute of Engineering. Bangalor...
2,2,E003,"B M S College of Engineering Basavanagudi,Ba...","B M S College of Engineering Basavanagudi,Ba..."
3,3,E004,Dr. Ambedkar Institute Of Technology Bangalore,Dr. Ambedkar Institute Of Technology Bangalo...
4,4,E005,R. V. College of Engineering Bangalore,R. V. College of Engineering Bangalore [E005]
...,...,...,...,...
214,214,E299,"Ghousia Institute of Technology for Women, Ba...","Ghousia Institute of Technology for Women, Ba..."
215,215,E300,AKASH INTITUTE OF ENGINEERING AND TECHNOLOGY ...,AKASH INTITUTE OF ENGINEERING AND TECHNOLOGY ...
216,216,E301,KISHKINDA UNIVERSITY BELLARI,KISHKINDA UNIVERSITY BELLARI [E301]
217,217,E302,"AMITY UNIVERSITY DEVANAHALLI ,BANAGLORE","AMITY UNIVERSITY DEVANAHALLI ,BANAGLORE [E302]"
218,218,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]"

In [59]:
college_details.drop( columns = ['Unnamed: 0', 'InstituteName'], inplace=True)

In [60]:
college_details[college_details['InstituteId'] == 'E001']['Institution']

0    University of Visvesvaraya College of Engineer...
Name: Institution, dtype: object

In [61]:
df4

,InstituteId,InstituteName,BranchCode,1G,1K,1R,2AG,2AK,2AR,2BG,...,GMK,GMR,SCG,SCK,SCR,STG,STK,STR,CourseName,course
0,E001,University of Visvesvaraya College of Engineer...,AI,10087,20801,0,9302,0,10041,12213,...,7979,8653,26148,0,33645,24190,0,33807,Artificial Intelligence and Machine Learning,Artificial Intelligence and Machine Learning [AI]
1,E001,University of Visvesvaraya College of Engineer...,CE,126281,0,140951,99176,0,110030,95076,...,84671,86716,105351,132307,186680,109874,0,129504,Civil Engineering,Civil Engineering [CE]
2,E001,University of Visvesvaraya College of Engineer...,CS,5809,0,0,5835,7296,6519,7166,...,6701,5402,20990,28206,29187,15475,16438,20958,Computers Science And Engineering,Computers Science And Engineering [CS]
3,E001,University of Visvesvaraya College of Engineer...,EC,15177,0,18548,14878,15407,16522,21600,...,14864,11936,33658,46591,47113,37482,0,52570,Electronics and Communication Engineering,Electronics and Communication Engineering [EC]
4,E001,University of Visvesvaraya College of Engineer...,EE,41399,0,55688,37226,39400,43302,59169,...,32204,31736,69595,73849,74966,72997,0,78257,Electrical And Electronics Engineering,Electrical And Electronics Engineering [EE]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LF,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (CLOUD,B TECH IN COMPUTER SCIENCE (CLOUD [LF]
1465,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LG,0,0,0,0,0,0,0,...,0,0,196735,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (CYBER SECURITY),B TECH IN COMPUTER SCIENCE (CYBER SECURITY) [LG]
1466,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LH,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (INFORMATION),B TECH IN COMPUTER SCIENCE (INFORMATION) [LH]
1467,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LJ,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYS...,BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYS...
1468,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LK,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS),B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS...

In [62]:
df5 = pd.merge(df4, college_details, on="InstituteId")

In [63]:
df5

,InstituteId,InstituteName,BranchCode,1G,1K,1R,2AG,2AK,2AR,2BG,...,GMR,SCG,SCK,SCR,STG,STK,STR,CourseName,course,Institution
0,E001,University of Visvesvaraya College of Engineer...,AI,10087,20801,0,9302,0,10041,12213,...,8653,26148,0,33645,24190,0,33807,Artificial Intelligence and Machine Learning,Artificial Intelligence and Machine Learning [AI],University of Visvesvaraya College of Engineer...
1,E001,University of Visvesvaraya College of Engineer...,CE,126281,0,140951,99176,0,110030,95076,...,86716,105351,132307,186680,109874,0,129504,Civil Engineering,Civil Engineering [CE],University of Visvesvaraya College of Engineer...
2,E001,University of Visvesvaraya College of Engineer...,CS,5809,0,0,5835,7296,6519,7166,...,5402,20990,28206,29187,15475,16438,20958,Computers Science And Engineering,Computers Science And Engineering [CS],University of Visvesvaraya College of Engineer...
3,E001,University of Visvesvaraya College of Engineer...,EC,15177,0,18548,14878,15407,16522,21600,...,11936,33658,46591,47113,37482,0,52570,Electronics and Communication Engineering,Electronics and Communication Engineering [EC],University of Visvesvaraya College of Engineer...
4,E001,University of Visvesvaraya College of Engineer...,EE,41399,0,55688,37226,39400,43302,59169,...,31736,69595,73849,74966,72997,0,78257,Electrical And Electronics Engineering,Electrical And Electronics Engineering [EE],University of Visvesvaraya College of Engineer...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LF,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (CLOUD,B TECH IN COMPUTER SCIENCE (CLOUD [LF],"G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]"
1465,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LG,0,0,0,0,0,0,0,...,0,196735,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (CYBER SECURITY),B TECH IN COMPUTER SCIENCE (CYBER SECURITY) [LG],"G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]"
1466,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LH,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (INFORMATION),B TECH IN COMPUTER SCIENCE (INFORMATION) [LH],"G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]"
1467,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LJ,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYS...,BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYS...,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]"
1468,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LK,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS),B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS...,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]"

In [64]:
df5.columns

Index(['InstituteId', 'InstituteName', 'BranchCode', '1G', '1K', '1R', '2AG',
       '2AK', '2AR', '2BG', '2BK', '2BR', '3AG', '3AK', '3AR', '3BG', '3BK',
       '3BR', 'GM', 'GMK', 'GMR', 'SCG', 'SCK', 'SCR', 'STG', 'STK', 'STR',
       'CourseName', 'course', 'Institution'],
      dtype='object')

In [65]:
df5

,InstituteId,InstituteName,BranchCode,1G,1K,1R,2AG,2AK,2AR,2BG,...,GMR,SCG,SCK,SCR,STG,STK,STR,CourseName,course,Institution
0,E001,University of Visvesvaraya College of Engineer...,AI,10087,20801,0,9302,0,10041,12213,...,8653,26148,0,33645,24190,0,33807,Artificial Intelligence and Machine Learning,Artificial Intelligence and Machine Learning [AI],University of Visvesvaraya College of Engineer...
1,E001,University of Visvesvaraya College of Engineer...,CE,126281,0,140951,99176,0,110030,95076,...,86716,105351,132307,186680,109874,0,129504,Civil Engineering,Civil Engineering [CE],University of Visvesvaraya College of Engineer...
2,E001,University of Visvesvaraya College of Engineer...,CS,5809,0,0,5835,7296,6519,7166,...,5402,20990,28206,29187,15475,16438,20958,Computers Science And Engineering,Computers Science And Engineering [CS],University of Visvesvaraya College of Engineer...
3,E001,University of Visvesvaraya College of Engineer...,EC,15177,0,18548,14878,15407,16522,21600,...,11936,33658,46591,47113,37482,0,52570,Electronics and Communication Engineering,Electronics and Communication Engineering [EC],University of Visvesvaraya College of Engineer...
4,E001,University of Visvesvaraya College of Engineer...,EE,41399,0,55688,37226,39400,43302,59169,...,31736,69595,73849,74966,72997,0,78257,Electrical And Electronics Engineering,Electrical And Electronics Engineering [EE],University of Visvesvaraya College of Engineer...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LF,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (CLOUD,B TECH IN COMPUTER SCIENCE (CLOUD [LF],"G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]"
1465,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LG,0,0,0,0,0,0,0,...,0,196735,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (CYBER SECURITY),B TECH IN COMPUTER SCIENCE (CYBER SECURITY) [LG],"G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]"
1466,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LH,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (INFORMATION),B TECH IN COMPUTER SCIENCE (INFORMATION) [LH],"G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]"
1467,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LJ,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYS...,BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYS...,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]"
1468,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE",LK,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS),B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS...,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]"

In [66]:

ordered_columns = [
    'InstituteId', 'InstituteName', 'Institution', 
    'CourseName', 'course', 'BranchCode', 
    '1G', '1K', '1R', 
    '2AG', '2AK', '2AR', 
    '2BG', '2BK', '2BR', 
    '3AG', '3AK', '3AR', 
    '3BG', '3BK', '3BR', 
    'GM', 'GMK', 'GMR', 
    'SCG', 'SCK', 'SCR', 
    'STG', 'STK', 'STR'
]

# Rearrange the DataFrame columns
df5 = df5.reindex(columns=ordered_columns)

In [67]:
df5

,InstituteId,InstituteName,Institution,CourseName,course,BranchCode,1G,1K,1R,2AG,...,3BR,GM,GMK,GMR,SCG,SCK,SCR,STG,STK,STR
0,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Artificial Intelligence and Machine Learning,Artificial Intelligence and Machine Learning [AI],AI,10087,20801,0,9302,...,0,6935,7979,8653,26148,0,33645,24190,0,33807
1,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Civil Engineering,Civil Engineering [CE],CE,126281,0,140951,99176,...,95251,74111,84671,86716,105351,132307,186680,109874,0,129504
2,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Computers Science And Engineering,Computers Science And Engineering [CS],CS,5809,0,0,5835,...,5708,4344,6701,5402,20990,28206,29187,15475,16438,20958
3,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Electronics and Communication Engineering,Electronics and Communication Engineering [EC],EC,15177,0,18548,14878,...,14664,9878,14864,11936,33658,46591,47113,37482,0,52570
4,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Electrical And Electronics Engineering,Electrical And Electronics Engineering [EE],EE,41399,0,55688,37226,...,34904,23821,32204,31736,69595,73849,74966,72997,0,78257
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (CLOUD,B TECH IN COMPUTER SCIENCE (CLOUD [LF],LF,0,0,0,0,...,0,196309,0,0,0,0,0,0,0,0
1465,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (CYBER SECURITY),B TECH IN COMPUTER SCIENCE (CYBER SECURITY) [LG],LG,0,0,0,0,...,0,182360,0,0,196735,0,0,0,0,0
1466,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (INFORMATION),B TECH IN COMPUTER SCIENCE (INFORMATION) [LH],LH,0,0,0,0,...,0,200270,0,0,0,0,0,0,0,0
1467,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYS...,BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYS...,LJ,0,0,0,0,...,0,196205,0,0,0,0,0,0,0,0
1468,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS),B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS...,LK,0,0,0,0,...,0,178340,0,0,0,0,0,0,0,0

In [1173]:
df5

,InstituteId,InstituteName,Institution,CourseName,course,BranchCode,1G,1K,1R,2AG,...,3BR,GM,GMK,GMR,SCG,SCK,SCR,STG,STK,STR
0,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Artificial Intelligence and Machine Learning,Artificial Intelligence and Machine Learning [AI],AI,10087,20801,0,9302,...,0,6935,7979,8653,26148,0,33645,24190,0,33807
1,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Civil Engineering,Civil Engineering [CE],CE,126281,0,140951,99176,...,95251,74111,84671,86716,105351,132307,186680,109874,0,129504
2,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Computers Science And Engineering,Computers Science And Engineering [CS],CS,5809,0,0,5835,...,5708,4344,6701,5402,20990,28206,29187,15475,16438,20958
3,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Electronics and Communication Engineering,Electronics and Communication Engineering [EC],EC,15177,0,18548,14878,...,14664,9878,14864,11936,33658,46591,47113,37482,0,52570
4,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Electrical And Electronics Engineering,Electrical And Electronics Engineering [EE],EE,41399,0,55688,37226,...,34904,23821,32204,31736,69595,73849,74966,72997,0,78257
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (CLOUD,B TECH IN COMPUTER SCIENCE (CLOUD [LF],LF,0,0,0,0,...,0,196309,0,0,0,0,0,0,0,0
1465,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (CYBER SECURITY),B TECH IN COMPUTER SCIENCE (CYBER SECURITY) [LG],LG,0,0,0,0,...,0,182360,0,0,196735,0,0,0,0,0
1466,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (INFORMATION),B TECH IN COMPUTER SCIENCE (INFORMATION) [LH],LH,0,0,0,0,...,0,200270,0,0,0,0,0,0,0,0
1467,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYS...,BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYS...,LJ,0,0,0,0,...,0,196205,0,0,0,0,0,0,0,0
1468,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS),B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS...,LK,0,0,0,0,...,0,178340,0,0,0,0,0,0,0,0

In [68]:
df5[ df5['BranchCode'] == '"A']

Empty DataFrame
Columns: [InstituteId, InstituteName, Institution, CourseName, course, BranchCode, 1G, 1K, 1R, 2AG, 2AK, 2AR, 2BG, 2BK, 2BR, 3AG, 3AK, 3AR, 3BG, 3BK, 3BR, GM, GMK, GMR, SCG, SCK, SCR, STG, STK, STR]
Index: []

[0 rows x 30 columns]

In [69]:
df5.rename(columns={'course': 'Course'}, inplace=True)

In [70]:
df5.to_csv(project_root / 'dataset' / 'college_cutoff_info.csv')

In [71]:
df5['BranchCode'].unique()

array(['AI', 'CE', 'CS', 'EC', 'EE', 'IE', 'ME', 'ST', 'TX', 'IM', 'EI',
       'ET', 'BT', 'CH', 'CY', 'DS', 'SE', 'AD', 'CA', 'MD', 'AE', 'AU',
       'CB', 'CD', 'IC', 'RI', 'EV', 'AM', 'BB', 'BJ', 'BO', 'BW', 'DB',
       'EB', 'OT', 'TC', 'CK', 'mn', 'BM', 'EN', 'IP', 'PT', 'EA', 'CF',
       'CO', 'CT', 'CR', 'MT', 'RA', 'CC', 'ES', 'ZC', 'BK', 'BP', 'RO',
       'MR', 'DC', 'MM', 'MK', 'IO', 'SA', 'BH', 'BL', 'CW', 'DG', 'BA',
       'BG', 'BU', 'CL', 'CN', 'CU', 'DD', 'DF', 'DK', 'AT', 'DA', 'DJ',
       'BN', 'BQ', 'BV', 'BX', 'BY', 'BZ', 'CM', 'CQ', 'CX', 'CZ', 'DE',
       'DM', 'DN', 'DH', 'UP', 'BR', 'CV', 'BF', 'DI', 'DL', 'LD', 'LE',
       'LF', 'LG', 'LH', 'LJ', 'LK'], dtype=object)

In [72]:
df5[ df5['BranchCode'] == 'In']

Empty DataFrame
Columns: [InstituteId, InstituteName, Institution, CourseName, Course, BranchCode, 1G, 1K, 1R, 2AG, 2AK, 2AR, 2BG, 2BK, 2BR, 3AG, 3AK, 3AR, 3BG, 3BK, 3BR, GM, GMK, GMR, SCG, SCK, SCR, STG, STK, STR]
Index: []

[0 rows x 30 columns]

In [73]:
df6 = df5

In [74]:
# Apply strip operation to all string columns
df6 = df6.map(lambda x: x.strip() if isinstance(x, str) else x)

In [75]:
df6

,InstituteId,InstituteName,Institution,CourseName,Course,BranchCode,1G,1K,1R,2AG,...,3BR,GM,GMK,GMR,SCG,SCK,SCR,STG,STK,STR
0,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Artificial Intelligence and Machine Learning,Artificial Intelligence and Machine Learning [AI],AI,10087,20801,0,9302,...,0,6935,7979,8653,26148,0,33645,24190,0,33807
1,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Civil Engineering,Civil Engineering [CE],CE,126281,0,140951,99176,...,95251,74111,84671,86716,105351,132307,186680,109874,0,129504
2,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Computers Science And Engineering,Computers Science And Engineering [CS],CS,5809,0,0,5835,...,5708,4344,6701,5402,20990,28206,29187,15475,16438,20958
3,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Electronics and Communication Engineering,Electronics and Communication Engineering [EC],EC,15177,0,18548,14878,...,14664,9878,14864,11936,33658,46591,47113,37482,0,52570
4,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Electrical And Electronics Engineering,Electrical And Electronics Engineering [EE],EE,41399,0,55688,37226,...,34904,23821,32204,31736,69595,73849,74966,72997,0,78257
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (CLOUD,B TECH IN COMPUTER SCIENCE (CLOUD [LF],LF,0,0,0,0,...,0,196309,0,0,0,0,0,0,0,0
1465,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (CYBER SECURITY),B TECH IN COMPUTER SCIENCE (CYBER SECURITY) [LG],LG,0,0,0,0,...,0,182360,0,0,196735,0,0,0,0,0
1466,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (INFORMATION),B TECH IN COMPUTER SCIENCE (INFORMATION) [LH],LH,0,0,0,0,...,0,200270,0,0,0,0,0,0,0,0
1467,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYST...,BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYST...,LJ,0,0,0,0,...,0,196205,0,0,0,0,0,0,0,0
1468,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS),B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS...,LK,0,0,0,0,...,0,178340,0,0,0,0,0,0,0,0

In [76]:
import json

# Assuming df is your DataFrame with a column named "Institution"

# Drop duplicates from the "Institution" column
unique_institutions = df6["Institution"].drop_duplicates().str.strip().sort_values().tolist()

# Create a dictionary with a single key "Institution" and the list of unique institutions as its value
data = {"Institution": unique_institutions}

# Specify the file path where you want to save the JSON file
file_path =  project_root  / "dropdown"  / "unique_institutions.json"

# Open the file in write mode and save the JSON data
with open(file_path, "w") as json_file:
    json.dump(data, json_file)

print("JSON data with unique institution names has been saved to:", file_path)

JSON data with unique institution names has been saved to: C:\Users\cheth\OneDrive\Desktop\Alloc8Me\dropdown\unique_institutions.json

In [77]:
import json

# Assuming df is your DataFrame with a column named "Course"

# Drop duplicates from the "Course" column
unique_courses = df6["Course"].drop_duplicates().str.strip().sort_values().tolist()

# Create a dictionary with a single key "Course" and the list of unique Course as its value
data = {"Course": unique_courses}

# Specify the file path where you want to save the JSON file
file_path =  project_root  / "dropdown"  / "unique_courses.json"

# Open the file in write mode and save the JSON data
with open(file_path, "w") as json_file:
    json.dump(data, json_file)

print("JSON data with unique course names has been saved to:", file_path)

JSON data with unique course names has been saved to: C:\Users\cheth\OneDrive\Desktop\Alloc8Me\dropdown\unique_courses.json

In [78]:
unique_loc_df

,CETCode,College,Location
1,E001,University Visveswariah College of Engineering,"KR Circle, Bengaluru"
2,E002,SKSJT Institute of Engineering,"Sampangi Rama Nagar, Bengaluru"
3,E003,BMS College of Engineering (Aided),"Basavanagudi, Bengaluru"
4,E004,Dr. Ambedkar Institute Of Technology (Aided),"Near Gnana Bharathi, Bengaluru"
5,E005,RV College of Engineering,"Mysuru Rd,Bengaluru"
...,...,...,...
202,E273,Government Engineering College,"Viprasainagar, Gangavathi, Koppal"
203,E274,Government Engineering College,"Moselehosahalli,Hassan"
204,E275,RV Institute of Technology and Management,"JP nagar,Bengaluru"
205,E278,Visvesvaraya Technological University (VTU),"Muddenahalli,Chickkaballapur"
206,E279,Visvesvaraya Technological University (VTU),Belgaum

In [79]:
# Perform a left join on InstituteId and CETCode
result_df = pd.merge(df6, unique_loc_df[['CETCode', 'Location']], left_on='InstituteId', right_on='CETCode', how='left')

# Drop the CETCode column from the result as it is redundant
result_df = result_df.drop(columns=['CETCode'])

In [80]:
result_df

,InstituteId,InstituteName,Institution,CourseName,Course,BranchCode,1G,1K,1R,2AG,...,GM,GMK,GMR,SCG,SCK,SCR,STG,STK,STR,Location
0,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Artificial Intelligence and Machine Learning,Artificial Intelligence and Machine Learning [AI],AI,10087,20801,0,9302,...,6935,7979,8653,26148,0,33645,24190,0,33807,"KR Circle, Bengaluru"
1,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Civil Engineering,Civil Engineering [CE],CE,126281,0,140951,99176,...,74111,84671,86716,105351,132307,186680,109874,0,129504,"KR Circle, Bengaluru"
2,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Computers Science And Engineering,Computers Science And Engineering [CS],CS,5809,0,0,5835,...,4344,6701,5402,20990,28206,29187,15475,16438,20958,"KR Circle, Bengaluru"
3,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Electronics and Communication Engineering,Electronics and Communication Engineering [EC],EC,15177,0,18548,14878,...,9878,14864,11936,33658,46591,47113,37482,0,52570,"KR Circle, Bengaluru"
4,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Electrical And Electronics Engineering,Electrical And Electronics Engineering [EE],EE,41399,0,55688,37226,...,23821,32204,31736,69595,73849,74966,72997,0,78257,"KR Circle, Bengaluru"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (CLOUD,B TECH IN COMPUTER SCIENCE (CLOUD [LF],LF,0,0,0,0,...,196309,0,0,0,0,0,0,0,0,NaN
1465,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (CYBER SECURITY),B TECH IN COMPUTER SCIENCE (CYBER SECURITY) [LG],LG,0,0,0,0,...,182360,0,0,196735,0,0,0,0,0,NaN
1466,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (INFORMATION),B TECH IN COMPUTER SCIENCE (INFORMATION) [LH],LH,0,0,0,0,...,200270,0,0,0,0,0,0,0,0,NaN
1467,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYST...,BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYST...,LJ,0,0,0,0,...,196205,0,0,0,0,0,0,0,0,NaN
1468,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS),B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS...,LK,0,0,0,0,...,178340,0,0,0,0,0,0,0,0,NaN

In [81]:
file_path = project_root / "dropdown" / "merged_loc_data.csv"
result_df.to_csv(file_path)

In [82]:
location_data = result_df

In [83]:
location_data = location_data [['InstituteId', 'Institution', 'Location' ]]

In [84]:
location_data = location_data.drop_duplicates(subset='InstituteId', keep='first')
location_data.reset_index(drop=True, inplace=True)

In [85]:
location_data.to_csv(project_root / "dropdown" / "not_imp_location_data.csv")

In [86]:
location_data

,InstituteId,Institution,Location
0,E001,University of Visvesvaraya College of Engineer...,"KR Circle, Bengaluru"
1,E002,S K S J T Institute of Engineering. Bangalore...,"Sampangi Rama Nagar, Bengaluru"
2,E003,"B M S College of Engineering Basavanagudi,Ban...","Basavanagudi, Bengaluru"
3,E004,Dr. Ambedkar Institute Of Technology Bangalor...,"Near Gnana Bharathi, Bengaluru"
4,E005,R. V. College of Engineering Bangalore [E005],"Mysuru Rd,Bengaluru"
...,...,...,...
214,E299,"Ghousia Institute of Technology for Women, Ban...",NaN
215,E300,AKASH INTITUTE OF ENGINEERING AND TECHNOLOGY ...,NaN
216,E301,KISHKINDA UNIVERSITY BELLARI [E301],NaN
217,E302,"AMITY UNIVERSITY DEVANAHALLI ,BANAGLORE [E302]",NaN
218,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",NaN

In [87]:
loc = pd.read_csv(project_root / "dropdown" / "location_data.csv")

In [88]:
# Apply strip operation to all string columns
loc = loc.map(lambda x: x.strip() if isinstance(x, str) else x)

In [89]:
loc['City'].astype(str).str.strip().unique()

array(['Bengaluru', 'Ramanagara', 'Chikkaballapur', 'Kolar', 'Tumakuru',
       'Mysore', 'Mandya', 'Hassan', 'Gadag', 'Belgaum', 'Bagalkot',
       'Haveri', 'Dharwad', 'Uttara Kannada', 'Bijapur', 'Gulbarga',
       'Bidar', 'Bellary', 'Raichur', 'Dakshina Kannada', 'Davanagere',
       'Chitradurga', 'Chikkamagaluru', 'Shivamogga', 'Kodagu',
       'Bengaluru Rural', 'Udupi', 'Chamarajanagara', 'Hubli', 'Karwar',
       'Yadagiri', 'Koppal', 'Kalburgi'], dtype=object)

In [90]:
type(loc)

pandas.core.frame.DataFrame

In [91]:
loc.columns

Index(['Unnamed: 0', 'InstituteId', 'Institution', 'Location', 'City'], dtype='object')

In [92]:
import json

# Assuming df is your DataFrame with a column named "Course"

# Drop duplicates from the "Course" column
unique_city = loc["City"].drop_duplicates().str.strip().sort_values().tolist()

# Create a dictionary with a single key "Course" and the list of unique Course as its value
data = {"City": unique_city}

# Specify the file path where you want to save the JSON file
file_path =  project_root  / "dropdown"  / "unique_city.json"

# Open the file in write mode and save the JSON data
with open(file_path, "w") as json_file:
    json.dump(data, json_file)

print("JSON data with unique course names has been saved to:", file_path)

JSON data with unique course names has been saved to: C:\Users\cheth\OneDrive\Desktop\Alloc8Me\dropdown\unique_city.json

In [93]:
data

{'City': ['Bagalkot',
  'Belgaum',
  'Bellary',
  'Bengaluru',
  'Bengaluru Rural',
  'Bidar',
  'Bijapur',
  'Chamarajanagara',
  'Chikkaballapur',
  'Chikkamagaluru',
  'Chitradurga',
  'Dakshina Kannada',
  'Davanagere',
  'Dharwad',
  'Gadag',
  'Gulbarga',
  'Hassan',
  'Haveri',
  'Hubli',
  'Kalburgi',
  'Karwar',
  'Kodagu',
  'Kolar',
  'Koppal',
  'Mandya',
  'Mysore',
  'Raichur',
  'Ramanagara',
  'Shivamogga',
  'Tumakuru',
  'Udupi',
  'Uttara Kannada',
  'Yadagiri']}

In [94]:
loc

,Unnamed: 0,InstituteId,Institution,Location,City
0,0,E001,University of Visvesvaraya College of Engineer...,"KR Circle, Bengaluru",Bengaluru
1,1,E002,S K S J T Institute of Engineering. Bangalore...,"Sampangi Rama Nagar, Bengaluru",Bengaluru
2,2,E003,"B M S College of Engineering Basavanagudi,Ban...","Basavanagudi, Bengaluru",Bengaluru
3,3,E004,Dr. Ambedkar Institute Of Technology Bangalor...,"Near Gnana Bharathi, Bengaluru",Bengaluru
4,4,E005,R. V. College of Engineering Bangalore [E005],"Mysuru Rd,Bengaluru",Bengaluru
...,...,...,...,...,...
214,214,E299,"Ghousia Institute of Technology for Women, Ban...",Bengaluru,Bengaluru
215,215,E300,AKASH INTITUTE OF ENGINEERING AND TECHNOLOGY ...,Bengaluru Rural,Bengaluru Rural
216,216,E301,KISHKINDA UNIVERSITY BELLARI [E301],Bellary,Bellary
217,217,E302,"AMITY UNIVERSITY DEVANAHALLI ,BANAGLORE [E302]",Bengaluru,Bengaluru
218,218,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",Davanagere,Davanagere

In [95]:
df6

,InstituteId,InstituteName,Institution,CourseName,Course,BranchCode,1G,1K,1R,2AG,...,3BR,GM,GMK,GMR,SCG,SCK,SCR,STG,STK,STR
0,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Artificial Intelligence and Machine Learning,Artificial Intelligence and Machine Learning [AI],AI,10087,20801,0,9302,...,0,6935,7979,8653,26148,0,33645,24190,0,33807
1,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Civil Engineering,Civil Engineering [CE],CE,126281,0,140951,99176,...,95251,74111,84671,86716,105351,132307,186680,109874,0,129504
2,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Computers Science And Engineering,Computers Science And Engineering [CS],CS,5809,0,0,5835,...,5708,4344,6701,5402,20990,28206,29187,15475,16438,20958
3,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Electronics and Communication Engineering,Electronics and Communication Engineering [EC],EC,15177,0,18548,14878,...,14664,9878,14864,11936,33658,46591,47113,37482,0,52570
4,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Electrical And Electronics Engineering,Electrical And Electronics Engineering [EE],EE,41399,0,55688,37226,...,34904,23821,32204,31736,69595,73849,74966,72997,0,78257
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (CLOUD,B TECH IN COMPUTER SCIENCE (CLOUD [LF],LF,0,0,0,0,...,0,196309,0,0,0,0,0,0,0,0
1465,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (CYBER SECURITY),B TECH IN COMPUTER SCIENCE (CYBER SECURITY) [LG],LG,0,0,0,0,...,0,182360,0,0,196735,0,0,0,0,0
1466,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (INFORMATION),B TECH IN COMPUTER SCIENCE (INFORMATION) [LH],LH,0,0,0,0,...,0,200270,0,0,0,0,0,0,0,0
1467,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYST...,BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYST...,LJ,0,0,0,0,...,0,196205,0,0,0,0,0,0,0,0
1468,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS),B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS...,LK,0,0,0,0,...,0,178340,0,0,0,0,0,0,0,0

In [96]:
loc

,Unnamed: 0,InstituteId,Institution,Location,City
0,0,E001,University of Visvesvaraya College of Engineer...,"KR Circle, Bengaluru",Bengaluru
1,1,E002,S K S J T Institute of Engineering. Bangalore...,"Sampangi Rama Nagar, Bengaluru",Bengaluru
2,2,E003,"B M S College of Engineering Basavanagudi,Ban...","Basavanagudi, Bengaluru",Bengaluru
3,3,E004,Dr. Ambedkar Institute Of Technology Bangalor...,"Near Gnana Bharathi, Bengaluru",Bengaluru
4,4,E005,R. V. College of Engineering Bangalore [E005],"Mysuru Rd,Bengaluru",Bengaluru
...,...,...,...,...,...
214,214,E299,"Ghousia Institute of Technology for Women, Ban...",Bengaluru,Bengaluru
215,215,E300,AKASH INTITUTE OF ENGINEERING AND TECHNOLOGY ...,Bengaluru Rural,Bengaluru Rural
216,216,E301,KISHKINDA UNIVERSITY BELLARI [E301],Bellary,Bellary
217,217,E302,"AMITY UNIVERSITY DEVANAHALLI ,BANAGLORE [E302]",Bengaluru,Bengaluru
218,218,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",Davanagere,Davanagere

In [110]:
df7 = pd.merge(df6, loc[['InstituteId', 'Location', 'City']], on='InstituteId', how='left')

In [111]:
df7.columns

Index(['InstituteId', 'InstituteName', 'Institution', 'CourseName', 'Course',
       'BranchCode', '1G', '1K', '1R', '2AG', '2AK', '2AR', '2BG', '2BK',
       '2BR', '3AG', '3AK', '3AR', '3BG', '3BK', '3BR', 'GM', 'GMK', 'GMR',
       'SCG', 'SCK', 'SCR', 'STG', 'STK', 'STR', 'Location', 'City'],
      dtype='object')

In [112]:
# Apply strip operation to all string columns
df7 = df7.map(lambda x: x.strip() if isinstance(x, str) else x)

In [113]:
df7

,InstituteId,InstituteName,Institution,CourseName,Course,BranchCode,1G,1K,1R,2AG,...,GMK,GMR,SCG,SCK,SCR,STG,STK,STR,Location,City
0,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Artificial Intelligence and Machine Learning,Artificial Intelligence and Machine Learning [AI],AI,10087,20801,0,9302,...,7979,8653,26148,0,33645,24190,0,33807,"KR Circle, Bengaluru",Bengaluru
1,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Civil Engineering,Civil Engineering [CE],CE,126281,0,140951,99176,...,84671,86716,105351,132307,186680,109874,0,129504,"KR Circle, Bengaluru",Bengaluru
2,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Computers Science And Engineering,Computers Science And Engineering [CS],CS,5809,0,0,5835,...,6701,5402,20990,28206,29187,15475,16438,20958,"KR Circle, Bengaluru",Bengaluru
3,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Electronics and Communication Engineering,Electronics and Communication Engineering [EC],EC,15177,0,18548,14878,...,14864,11936,33658,46591,47113,37482,0,52570,"KR Circle, Bengaluru",Bengaluru
4,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Electrical And Electronics Engineering,Electrical And Electronics Engineering [EE],EE,41399,0,55688,37226,...,32204,31736,69595,73849,74966,72997,0,78257,"KR Circle, Bengaluru",Bengaluru
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (CLOUD,B TECH IN COMPUTER SCIENCE (CLOUD [LF],LF,0,0,0,0,...,0,0,0,0,0,0,0,0,Davanagere,Davanagere
1465,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (CYBER SECURITY),B TECH IN COMPUTER SCIENCE (CYBER SECURITY) [LG],LG,0,0,0,0,...,0,0,196735,0,0,0,0,0,Davanagere,Davanagere
1466,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (INFORMATION),B TECH IN COMPUTER SCIENCE (INFORMATION) [LH],LH,0,0,0,0,...,0,0,0,0,0,0,0,0,Davanagere,Davanagere
1467,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYST...,BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYST...,LJ,0,0,0,0,...,0,0,0,0,0,0,0,0,Davanagere,Davanagere
1468,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS),B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS...,LK,0,0,0,0,...,0,0,0,0,0,0,0,0,Davanagere,Davanagere

In [114]:
df7.to_csv(project_root / 'dataset' / 'dataset.csv')

In [115]:
df7.columns

Index(['InstituteId', 'InstituteName', 'Institution', 'CourseName', 'Course',
       'BranchCode', '1G', '1K', '1R', '2AG', '2AK', '2AR', '2BG', '2BK',
       '2BR', '3AG', '3AK', '3AR', '3BG', '3BK', '3BR', 'GM', 'GMK', 'GMR',
       'SCG', 'SCK', 'SCR', 'STG', 'STK', 'STR', 'Location', 'City'],
      dtype='object')

In [116]:
ordered_columns = ['InstituteId', 'InstituteName', 'Institution', 'CourseName', 'Course',
       'Location', 'City', 'BranchCode', '1G', '1K', '1R', '2AG', '2AK', '2AR', '2BG', '2BK',
       '2BR', '3AG', '3AK', '3AR', '3BG', '3BK', '3BR', 'GM', 'GMK', 'GMR',
       'SCG', 'SCK', 'SCR', 'STG', 'STK', 'STR']

# Rearrange the DataFrame columns
df7 = df7.reindex(columns=ordered_columns)

In [117]:
df7

,InstituteId,InstituteName,Institution,CourseName,Course,Location,City,BranchCode,1G,1K,...,3BR,GM,GMK,GMR,SCG,SCK,SCR,STG,STK,STR
0,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Artificial Intelligence and Machine Learning,Artificial Intelligence and Machine Learning [AI],"KR Circle, Bengaluru",Bengaluru,AI,10087,20801,...,0,6935,7979,8653,26148,0,33645,24190,0,33807
1,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Civil Engineering,Civil Engineering [CE],"KR Circle, Bengaluru",Bengaluru,CE,126281,0,...,95251,74111,84671,86716,105351,132307,186680,109874,0,129504
2,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Computers Science And Engineering,Computers Science And Engineering [CS],"KR Circle, Bengaluru",Bengaluru,CS,5809,0,...,5708,4344,6701,5402,20990,28206,29187,15475,16438,20958
3,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Electronics and Communication Engineering,Electronics and Communication Engineering [EC],"KR Circle, Bengaluru",Bengaluru,EC,15177,0,...,14664,9878,14864,11936,33658,46591,47113,37482,0,52570
4,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Electrical And Electronics Engineering,Electrical And Electronics Engineering [EE],"KR Circle, Bengaluru",Bengaluru,EE,41399,0,...,34904,23821,32204,31736,69595,73849,74966,72997,0,78257
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (CLOUD,B TECH IN COMPUTER SCIENCE (CLOUD [LF],Davanagere,Davanagere,LF,0,0,...,0,196309,0,0,0,0,0,0,0,0
1465,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (CYBER SECURITY),B TECH IN COMPUTER SCIENCE (CYBER SECURITY) [LG],Davanagere,Davanagere,LG,0,0,...,0,182360,0,0,196735,0,0,0,0,0
1466,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (INFORMATION),B TECH IN COMPUTER SCIENCE (INFORMATION) [LH],Davanagere,Davanagere,LH,0,0,...,0,200270,0,0,0,0,0,0,0,0
1467,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYST...,BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYST...,Davanagere,Davanagere,LJ,0,0,...,0,196205,0,0,0,0,0,0,0,0
1468,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS),B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS...,Davanagere,Davanagere,LK,0,0,...,0,178340,0,0,0,0,0,0,0,0

In [118]:
# Apply strip operation to all string columns
df7 = df7.map(lambda x: x.strip() if isinstance(x, str) else x)

In [119]:
df7.to_csv(project_root / 'dataset' / 'dataset.csv')

In [122]:
import json

# Assuming df is your DataFrame with a column named "Course"

# Drop duplicates from the "Course" column
unique_courses = df7["Course"].drop_duplicates().str.strip().sort_values().tolist()

# Create a dictionary with a single key "Course" and the list of unique Course as its value
data = {"Course": unique_courses}

# Specify the file path where you want to save the JSON file
file_path =  project_root  / "dropdown"  / "unique_courses.json"

# Open the file in write mode and save the JSON data
with open(file_path, "w") as json_file:
    json.dump(data, json_file)

print("JSON data with unique course names has been saved to:", file_path)

JSON data with unique course names has been saved to: C:\Users\cheth\OneDrive\Desktop\Alloc8Me\dropdown\unique_courses.json

In [123]:
import json

# Assuming df is your DataFrame with a column named "Institution"

# Drop duplicates from the "Institution" column
unique_institutions = df7["Institution"].drop_duplicates().str.strip().sort_values().tolist()

# Create a dictionary with a single key "Institution" and the list of unique institutions as its value
data = {"Institution": unique_institutions}

# Specify the file path where you want to save the JSON file
file_path =  project_root  / "dropdown"  / "unique_institutions.json"

# Open the file in write mode and save the JSON data
with open(file_path, "w") as json_file:
    json.dump(data, json_file)

print("JSON data with unique institution names has been saved to:", file_path)

JSON data with unique institution names has been saved to: C:\Users\cheth\OneDrive\Desktop\Alloc8Me\dropdown\unique_institutions.json

In [124]:
df7.columns

Index(['InstituteId', 'InstituteName', 'Institution', 'CourseName', 'Course',
       'Location', 'City', 'BranchCode', '1G', '1K', '1R', '2AG', '2AK', '2AR',
       '2BG', '2BK', '2BR', '3AG', '3AK', '3AR', '3BG', '3BK', '3BR', 'GM',
       'GMK', 'GMR', 'SCG', 'SCK', 'SCR', 'STG', 'STK', 'STR'],
      dtype='object')

In [125]:
df8 = df7

In [127]:
import numpy as np

In [128]:
# List of columns to consider for cutoff ranks
cutoff_columns = ['1G', '1K', '1R', '2AG', '2AK', '2AR', '2BG', '2BK', '2BR', '3AG', '3AK', '3AR', '3BG', '3BK', '3BR', 'GM', 'GMK', 'GMR', 'SCG', 'SCK', 'SCR', 'STG', 'STK', 'STR']

# Calculate average cutoff rank ignoring zeros and store as integer
df8['AvgCutoffRank'] = df8[cutoff_columns].replace(0, np.nan).mean(axis=1).fillna(0).astype(int)

In [150]:
df8

,InstituteId,InstituteName,Institution,CourseName,Course,Location,City,BranchCode,1G,1K,...,GM,GMK,GMR,SCG,SCK,SCR,STG,STK,STR,AvgCutoffRank
0,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Artificial Intelligence and Machine Learning,Artificial Intelligence and Machine Learning [AI],"KR Circle, Bengaluru",Bengaluru,AI,10087,20801,...,6935,7979,8653,26148,0,33645,24190,0,33807,15627
1,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Civil Engineering,Civil Engineering [CE],"KR Circle, Bengaluru",Bengaluru,CE,126281,0,...,74111,84671,86716,105351,132307,186680,109874,0,129504,110359
2,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Computers Science And Engineering,Computers Science And Engineering [CS],"KR Circle, Bengaluru",Bengaluru,CS,5809,0,...,4344,6701,5402,20990,28206,29187,15475,16438,20958,11266
3,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Electronics and Communication Engineering,Electronics and Communication Engineering [EC],"KR Circle, Bengaluru",Bengaluru,EC,15177,0,...,9878,14864,11936,33658,46591,47113,37482,0,52570,22494
4,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Electrical And Electronics Engineering,Electrical And Electronics Engineering [EE],"KR Circle, Bengaluru",Bengaluru,EE,41399,0,...,23821,32204,31736,69595,73849,74966,72997,0,78257,53126
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (CLOUD,B TECH IN COMPUTER SCIENCE (CLOUD [LF],Davanagere,Davanagere,LF,0,0,...,196309,0,0,0,0,0,0,0,0,196309
1465,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (CYBER SECURITY),B TECH IN COMPUTER SCIENCE (CYBER SECURITY) [LG],Davanagere,Davanagere,LG,0,0,...,182360,0,0,196735,0,0,0,0,0,189547
1466,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (INFORMATION),B TECH IN COMPUTER SCIENCE (INFORMATION) [LH],Davanagere,Davanagere,LH,0,0,...,200270,0,0,0,0,0,0,0,0,200270
1467,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYST...,BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYST...,Davanagere,Davanagere,LJ,0,0,...,196205,0,0,0,0,0,0,0,0,196205
1468,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS),B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS...,Davanagere,Davanagere,LK,0,0,...,178340,0,0,0,0,0,0,0,0,178340

In [183]:
df8.to_csv(project_root / 'streamlit_assets'/ 'not_sorted_option_entry.csv')

In [184]:
df9 = df8

In [185]:
# Sorting the dataframe by average cutoff rank in ascending order
df9 = df9.sort_values(by='AvgCutoffRank')

In [186]:
df9

,InstituteId,InstituteName,Institution,CourseName,Course,Location,City,BranchCode,1G,1K,...,GM,GMK,GMR,SCG,SCK,SCR,STG,STK,STR,AvgCutoffRank
686,E112,Sri Krishna Institute of Technology Bangalore,Sri Krishna Institute of Technology Bangalore...,Civil Engineering,Civil Engineering [CE],"Chikkabanavara, Bengaluru",Bengaluru,CE,0,0,...,0,0,0,0,0,0,0,0,0,0
1029,E174,Dr. Sri. Sri. Sri. Shivakumara Mahaswamyji Col...,Dr. Sri. Sri. Sri. Shivakumara Mahaswamyji Col...,Civil Engineering,Civil Engineering [CE],"Kammasandra, Bengaluru Rural",Bengaluru Rural,CE,0,0,...,0,0,0,0,0,0,0,0,0,0
1034,E174,Dr. Sri. Sri. Sri. Shivakumara Mahaswamyji Col...,Dr. Sri. Sri. Sri. Shivakumara Mahaswamyji Col...,Mechanical Engineering,Mechanical Engineering [ME],"Kammasandra, Bengaluru Rural",Bengaluru Rural,ME,0,0,...,0,0,0,0,0,0,0,0,0,0
1037,E175,S.G.Balekundri Institute of Technology Belgaum,S.G.Balekundri Institute of Technology Belgau...,Civil Engineering,Civil Engineering [CE],Belgaum,Belgaum,CE,0,0,...,0,0,0,0,0,0,0,0,0,0
1366,E260,Nitte School of Architecture YELAHANKA BANGALORE,Nitte School of Architecture YELAHANKA BANGAL...,DESIGN,DESIGN [DG],"Yelahanka,Bengaluru",Bengaluru,DG,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1075,E184,C Byre Gowda Institute of Technology Kolar,C Byre Gowda Institute of Technology Kolar [E...,Computer Engineering,Computer Engineering [CO],Kolar,Kolar,CO,0,0,...,203287,0,0,0,0,0,0,0,0,203287
445,E075,Ballari Institute of Technology and Management...,Ballari Institute of Technology and Management...,Civil Engineering,Civil Engineering [CE],"Near Allipur, Bellary",Bellary,CE,0,0,...,203288,0,0,0,0,0,0,0,0,203288
1408,E281,"Government Engineering College Challakere,Chi...","Government Engineering College Challakere,Chi...",Automobile Engineering,Automobile Engineering [AU],Chitradurga,Chitradurga,AU,0,0,...,203325,0,0,0,0,0,0,0,0,203325
834,E139,Impact College of Engineering and Applied Scie...,Impact College of Engineering and Applied Scie...,Automation and Robotics Engineering,Automation and Robotics Engineering [RO],"Sahakara Nagar, Bengaluru",Bengaluru,RO,0,0,...,203331,0,0,0,0,0,0,0,0,203331
214,E031,Basaveshwara Engineering College Bagalkot,Basaveshwara Engineering College Bagalkot [E031],Mechanical Engineering,Mechanical Engineering [ME],"Vidayagiri, Bagalkot",Bagalkot,ME,0,0,...,203368,0,0,0,0,0,0,0,0,203368

In [187]:
df9.to_csv(project_root / 'streamlit_assets'/ 'sorted_option_entry.csv')

In [188]:
df8.columns

Index(['InstituteId', 'InstituteName', 'Institution', 'CourseName', 'Course',
       'Location', 'City', 'BranchCode', '1G', '1K', '1R', '2AG', '2AK', '2AR',
       '2BG', '2BK', '2BR', '3AG', '3AK', '3AR', '3BG', '3BK', '3BR', 'GM',
       'GMK', 'GMR', 'SCG', 'SCK', 'SCR', 'STG', 'STK', 'STR',
       'AvgCutoffRank'],
      dtype='object')

In [202]:
df9[ (df9['BranchCode'] == 'CS') & ( df9['City'] == 'Bengaluru') ]

,InstituteId,InstituteName,Institution,CourseName,Course,Location,City,BranchCode,1G,1K,...,GM,GMK,GMR,SCG,SCK,SCR,STG,STK,STR,AvgCutoffRank
29,E005,R. V. College of Engineering Bangalore,R. V. College of Engineering Bangalore [E005],Computers Science And Engineering,Computers Science And Engineering [CS],"Mysuru Rd,Bengaluru",Bengaluru,CS,749,0,...,360,1659,800,6380,11447,10358,7132,27929,11075,4522
46,E006,M S Ramaiah Institute of Technology Bangalore,M S Ramaiah Institute of Technology Bangalore...,Computers Science And Engineering,Computers Science And Engineering [CS],"MSRIT Post,Bengaluru",Bengaluru,CS,3085,0,...,1859,3592,3045,12563,16313,14402,13465,0,23343,7247
322,E048,"B M S College of Engineering Basavanagudi,Ban...","B M S College of Engineering Basavanagudi,Ban...",Computers Science And Engineering,Computers Science And Engineering [CS],"Basavanagudi,Bengaluru",Bengaluru,CS,2623,0,...,1037,3057,1817,13450,17704,18099,14210,27763,22641,7715
2,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Computers Science And Engineering,Computers Science And Engineering [CS],"KR Circle, Bengaluru",Bengaluru,CS,5809,0,...,4344,6701,5402,20990,28206,29187,15475,16438,20958,11266
64,E007,Dayananda Sagar College of Engineering Bangalore,Dayananda Sagar College of Engineering Bangal...,Computers Science And Engineering,Computers Science And Engineering [CS],"Kumaraswamy Layout, Bengaluru",Bengaluru,CS,7081,0,...,4424,7987,5914,23711,34430,31745,17034,32849,24935,13617
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1437,E297,ADITYA COLLEGE OF ENGINEERING AND TECHNOLOGY ...,ADITYA COLLEGE OF ENGINEERING AND TECHNOLOGY ...,Computers Science And Engineering,Computers Science And Engineering [CS],Bengaluru,Bengaluru,CS,99268,0,...,87081,0,0,115201,0,165806,0,0,0,108112
1098,E188,Vijaya Vittala Institute of Technology Bangalore,Vijaya Vittala Institute of Technology Bangal...,Computers Science And Engineering,Computers Science And Engineering [CS],"Kothanur, Bengaluru",Bengaluru,CS,0,0,...,80222,0,0,112173,0,0,0,0,153849,109109
771,E127,M S Engineering College Bangalore Urban,M S Engineering College Bangalore Urban [E127],Computers Science And Engineering,Computers Science And Engineering [CS],"Off Bengaluru International Airport, Bengaluru",Bengaluru,CS,93348,0,...,86073,87513,92884,132179,159331,180649,155617,0,0,115312
995,E168,Amrutha Institute of Engineering and Mangement...,Amrutha Institute of Engineering and Mangement...,Computers Science And Engineering,Computers Science And Engineering [CS],"Bidadi,Bengaluru",Bengaluru,CS,0,0,...,86239,112592,101193,132124,0,140142,159168,0,199525,120714
1442,E299,"Ghousia Institute of Technology for Women, Ban...","Ghousia Institute of Technology for Women, Ban...",Computers Science And Engineering,Computers Science And Engineering [CS],Bengaluru,Bengaluru,CS,0,0,...,125837,0,131320,167815,0,188598,162861,0,0,149632

In [198]:
df9[(df9['BranchCode'] == 'CS') & (df9['City'].isin(['Mandya']))]

,InstituteId,InstituteName,Institution,CourseName,Course,Location,City,BranchCode,1G,1K,...,GM,GMK,GMR,SCG,SCK,SCR,STG,STK,STR,AvgCutoffRank
365,E058,P E S College of Engineering Mandya,P E S College of Engineering Mandya [E058],Computers Science And Engineering,Computers Science And Engineering [CS],"P.E.S. Engineering College Road, Mandya",Mandya,CS,28223,0,...,17729,19290,21608,46829,98277,49342,39832,0,36500,32973
942,E158,Maharaja Institute of Technology-Mysore Belaw...,Maharaja Institute of Technology-Mysore Belaw...,Computers Science And Engineering,Computers Science And Engineering [CS],"Belawadi, Mandya",Mandya,CS,38222,0,...,30564,53821,35766,68500,0,78642,62105,0,98193,51014
930,E156,"Government Engineering College K R Pet, Mandy...","Government Engineering College K R Pet, Mandy...",Computers Science And Engineering,Computers Science And Engineering [CS],"K R Pet, Mandya",Mandya,CS,55567,0,...,52245,56358,56594,72736,0,75311,71308,0,81134,67013
840,E142,Adichunchanagiri University(Formerly BGSIT) N...,Adichunchanagiri University(Formerly BGSIT) N...,Computers Science And Engineering,Computers Science And Engineering [CS],"Nagamangala ,Mandya",Mandya,CS,51278,0,...,35859,45847,45692,92253,123269,96102,134841,0,154242,72957
1202,E210,G Madegowda Institute of Technology Maddur Ta...,G Madegowda Institute of Technology Maddur Ta...,Computers Science And Engineering,Computers Science And Engineering [CS],"Maddur , Mandya",Mandya,CS,92009,0,...,73344,87523,76901,123935,0,159736,155186,0,0,100953
1303,E238,Mysuru Royal Institute of Technology Mandya (D),Mysuru Royal Institute of Technology Mandya (...,Computers Science And Engineering,Computers Science And Engineering [CS],Mandya,Mandya,CS,0,0,...,88607,109812,94797,124479,0,149385,116863,0,125542,114895
1251,E227,Cauvery Institute of Technology Mandya tq,Cauvery Institute of Technology Mandya tq [E227],Computers Science And Engineering,Computers Science And Engineering [CS],Mandya,Mandya,CS,97232,0,...,87639,94992,108259,164926,139263,174694,167867,0,0,135058

In [199]:
df9[ df9['InstituteId'] == 'E142' ]

,InstituteId,InstituteName,Institution,CourseName,Course,Location,City,BranchCode,1G,1K,...,GM,GMK,GMR,SCG,SCK,SCR,STG,STK,STR,AvgCutoffRank
840,E142,Adichunchanagiri University(Formerly BGSIT) N...,Adichunchanagiri University(Formerly BGSIT) N...,Computers Science And Engineering,Computers Science And Engineering [CS],"Nagamangala ,Mandya",Mandya,CS,51278,0,...,35859,45847,45692,92253,123269,96102,134841,0,154242,72957
842,E142,Adichunchanagiri University(Formerly BGSIT) N...,Adichunchanagiri University(Formerly BGSIT) N...,Information Science and Engineering,Information Science and Engineering [IE],"Nagamangala ,Mandya",Mandya,IE,0,0,...,44423,56524,45897,151820,0,0,177216,0,0,77199
841,E142,Adichunchanagiri University(Formerly BGSIT) N...,Adichunchanagiri University(Formerly BGSIT) N...,Electronics and Communication Engineering,Electronics and Communication Engineering [EC],"Nagamangala ,Mandya",Mandya,EC,79512,0,...,52995,77744,61471,163162,187129,0,121007,0,0,97360
838,E142,Adichunchanagiri University(Formerly BGSIT) N...,Adichunchanagiri University(Formerly BGSIT) N...,Artificial Intelligence and Machine Learning,Artificial Intelligence and Machine Learning [AI],"Nagamangala ,Mandya",Mandya,AI,66487,0,...,51554,0,61352,138634,0,177857,120901,0,0,100860
839,E142,Adichunchanagiri University(Formerly BGSIT) N...,Adichunchanagiri University(Formerly BGSIT) N...,Civil Engineering,Civil Engineering [CE],"Nagamangala ,Mandya",Mandya,CE,0,0,...,195962,0,0,0,0,0,0,0,0,195962
843,E142,Adichunchanagiri University(Formerly BGSIT) N...,Adichunchanagiri University(Formerly BGSIT) N...,Mechanical Engineering,Mechanical Engineering [ME],"Nagamangala ,Mandya",Mandya,ME,0,0,...,201076,0,0,0,0,0,0,0,0,201076

In [204]:
df9.columns

Index(['InstituteId', 'InstituteName', 'Institution', 'CourseName', 'Course',
       'Location', 'City', 'BranchCode', '1G', '1K', '1R', '2AG', '2AK', '2AR',
       '2BG', '2BK', '2BR', '3AG', '3AK', '3AR', '3BG', '3BK', '3BR', 'GM',
       'GMK', 'GMR', 'SCG', 'SCK', 'SCR', 'STG', 'STK', 'STR',
       'AvgCutoffRank'],
      dtype='object')

In [205]:
df10 = df9

In [207]:
result_df

,InstituteId,InstituteName,Institution,CourseName,Course,Location,City,BranchCode,1G,1K,...,Category-3A_min,Category-3A_max,Category-3B_min,Category-3B_max,Category-GM_min,Category-GM_max,Category-SC_min,Category-SC_max,Category-ST_min,Category-ST_max
686,E112,Sri Krishna Institute of Technology Bangalore,Sri Krishna Institute of Technology Bangalore...,Civil Engineering,Civil Engineering [CE],"Chikkabanavara, Bengaluru",Bengaluru,CE,0,0,...,0,0,0,0,0,0,0,0,0,0
1029,E174,Dr. Sri. Sri. Sri. Shivakumara Mahaswamyji Col...,Dr. Sri. Sri. Sri. Shivakumara Mahaswamyji Col...,Civil Engineering,Civil Engineering [CE],"Kammasandra, Bengaluru Rural",Bengaluru Rural,CE,0,0,...,0,0,0,0,0,0,0,0,0,0
1034,E174,Dr. Sri. Sri. Sri. Shivakumara Mahaswamyji Col...,Dr. Sri. Sri. Sri. Shivakumara Mahaswamyji Col...,Mechanical Engineering,Mechanical Engineering [ME],"Kammasandra, Bengaluru Rural",Bengaluru Rural,ME,0,0,...,0,0,0,0,0,0,0,0,0,0
1037,E175,S.G.Balekundri Institute of Technology Belgaum,S.G.Balekundri Institute of Technology Belgau...,Civil Engineering,Civil Engineering [CE],Belgaum,Belgaum,CE,0,0,...,0,0,0,0,0,0,0,0,0,0
1366,E260,Nitte School of Architecture YELAHANKA BANGALORE,Nitte School of Architecture YELAHANKA BANGAL...,DESIGN,DESIGN [DG],"Yelahanka,Bengaluru",Bengaluru,DG,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1075,E184,C Byre Gowda Institute of Technology Kolar,C Byre Gowda Institute of Technology Kolar [E...,Computer Engineering,Computer Engineering [CO],Kolar,Kolar,CO,0,0,...,0,0,0,0,203287,203287,0,0,0,0
445,E075,Ballari Institute of Technology and Management...,Ballari Institute of Technology and Management...,Civil Engineering,Civil Engineering [CE],"Near Allipur, Bellary",Bellary,CE,0,0,...,0,0,0,0,203288,203288,0,0,0,0
1408,E281,"Government Engineering College Challakere,Chi...","Government Engineering College Challakere,Chi...",Automobile Engineering,Automobile Engineering [AU],Chitradurga,Chitradurga,AU,0,0,...,0,0,0,0,203325,203325,0,0,0,0
834,E139,Impact College of Engineering and Applied Scie...,Impact College of Engineering and Applied Scie...,Automation and Robotics Engineering,Automation and Robotics Engineering [RO],"Sahakara Nagar, Bengaluru",Bengaluru,RO,0,0,...,0,0,0,0,203331,203331,0,0,0,0
214,E031,Basaveshwara Engineering College Bagalkot,Basaveshwara Engineering College Bagalkot [E031],Mechanical Engineering,Mechanical Engineering [ME],"Vidayagiri, Bagalkot",Bagalkot,ME,0,0,...,0,0,0,0,203368,203368,0,0,0,0

In [208]:
result_df.to_csv("dummy.csv")

In [212]:
df11 = pd.read_csv( project_root / 'assets' / 'dataset.csv')

In [213]:
df11

,Unnamed: 0,InstituteId,InstituteName,Institution,CourseName,Course,Location,City,BranchCode,1G,...,GM,GMK,GMR,SCG,SCK,SCR,STG,STK,STR,AvgCutoffRank
0,0,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Artificial Intelligence and Machine Learning,Artificial Intelligence and Machine Learning [AI],"KR Circle, Bengaluru",Bengaluru,AI,10087,...,6935,7979,8653,26148,0,33645,24190,0,33807,15627
1,1,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Civil Engineering,Civil Engineering [CE],"KR Circle, Bengaluru",Bengaluru,CE,126281,...,74111,84671,86716,105351,132307,186680,109874,0,129504,110359
2,2,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Computers Science And Engineering,Computers Science And Engineering [CS],"KR Circle, Bengaluru",Bengaluru,CS,5809,...,4344,6701,5402,20990,28206,29187,15475,16438,20958,11266
3,3,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Electronics and Communication Engineering,Electronics and Communication Engineering [EC],"KR Circle, Bengaluru",Bengaluru,EC,15177,...,9878,14864,11936,33658,46591,47113,37482,0,52570,22494
4,4,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Electrical And Electronics Engineering,Electrical And Electronics Engineering [EE],"KR Circle, Bengaluru",Bengaluru,EE,41399,...,23821,32204,31736,69595,73849,74966,72997,0,78257,53126
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,1464,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (CLOUD,B TECH IN COMPUTER SCIENCE (CLOUD [LF],Davanagere,Davanagere,LF,0,...,196309,0,0,0,0,0,0,0,0,196309
1465,1465,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (CYBER SECURITY),B TECH IN COMPUTER SCIENCE (CYBER SECURITY) [LG],Davanagere,Davanagere,LG,0,...,182360,0,0,196735,0,0,0,0,0,189547
1466,1466,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (INFORMATION),B TECH IN COMPUTER SCIENCE (INFORMATION) [LH],Davanagere,Davanagere,LH,0,...,200270,0,0,0,0,0,0,0,0,200270
1467,1467,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYST...,BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYST...,Davanagere,Davanagere,LJ,0,...,196205,0,0,0,0,0,0,0,0,196205
1468,1468,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS),B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS...,Davanagere,Davanagere,LK,0,...,178340,0,0,0,0,0,0,0,0,178340

In [214]:
# Define mappings from columns to categories
category_mappings = {
    'Category-1': ['1G', '1K', '1R'],
    'Category-2A': ['2AG', '2AK', '2AR'],
    'Category-2B': ['2BG', '2BK', '2BR'],
    'Category-3A': ['3AG', '3AK', '3AR'],
    'Category-3B': ['3BG', '3BK', '3BR'],
    'Category-GM': ['GM', 'GMK', 'GMR'],
    'Category-SC': ['SCG', 'SCK', 'SCR'],
    'Category-ST': ['STG', 'STK', 'STR']
}

# Initialize an empty DataFrame to store results
result_df = df11.copy()

# Calculate minimum and maximum cutoff rank for each category
for category, columns in category_mappings.items():
    # Replace zeros with NaN to ignore them in min/max calculation
    replaced_df = df11[columns].replace(0, pd.NA)
    
    # Calculate the minimum and maximum values for each row in the category
    min_values = replaced_df.min(axis=1)
    max_values = replaced_df.max(axis=1)
    
    # Replace NaN with 0 (if all values in row were zero)
    min_values = min_values.fillna(0)
    max_values = max_values.fillna(0)
    
    # Assign the minimum and maximum values to the result dataframe
    result_df[f'{category}_min'] = min_values
    result_df[f'{category}_max'] = max_values

C:\Users\cheth\AppData\Local\Temp\ipykernel_2396\3997574641.py:26: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  min_values = min_values.fillna(0)
C:\Users\cheth\AppData\Local\Temp\ipykernel_2396\3997574641.py:27: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  max_values = max_values.fillna(0)
C:\Users\cheth\AppData\Local\Temp\ipykernel_2396\3997574641.py:26: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  min_values = min_values.fillna(0)
C:\Users\cheth\AppData\Local\Temp\ipykernel_2396\3997574641.py:27: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  max_values = max_values.fillna(0)
C:\Users\cheth\AppData\Local\Temp\ipykernel_2396\3997574641.py:26: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  min_values = min_values.fillna(0)
C:\Users\cheth\AppData\Local\Temp\ipykernel_2396\3997574641.py:27: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  max_values = max_values.fillna(0)
C:\Users\cheth\AppData\Local\Temp\ipykernel_2396\3997574641.py:26: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  min_values = min_values.fillna(0)
C:\Users\cheth\AppData\Local\Temp\ipykernel_2396\3997574641.py:27: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  max_values = max_values.fillna(0)
C:\Users\cheth\AppData\Local\Temp\ipykernel_2396\3997574641.py:26: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  min_values = min_values.fillna(0)
C:\Users\cheth\AppData\Local\Temp\ipykernel_2396\3997574641.py:27: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  max_values = max_values.fillna(0)
C:\Users\cheth\AppData\Local\Temp\ipykernel_2396\3997574641.py:26: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  min_values = min_values.fillna(0)
C:\Users\cheth\AppData\Local\Temp\ipykernel_2396\3997574641.py:27: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  max_values = max_values.fillna(0)
C:\Users\cheth\AppData\Local\Temp\ipykernel_2396\3997574641.py:26: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  min_values = min_values.fillna(0)
C:\Users\cheth\AppData\Local\Temp\ipykernel_2396\3997574641.py:27: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  max_values = max_values.fillna(0)
C:\Users\cheth\AppData\Local\Temp\ipykernel_2396\3997574641.py:26: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  min_values = min_values.fillna(0)
C:\Users\cheth\AppData\Local\Temp\ipykernel_2396\3997574641.py:27: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  max_values = max_values.fillna(0)

In [215]:
result_df

,Unnamed: 0,InstituteId,InstituteName,Institution,CourseName,Course,Location,City,BranchCode,1G,...,Category-3A_min,Category-3A_max,Category-3B_min,Category-3B_max,Category-GM_min,Category-GM_max,Category-SC_min,Category-SC_max,Category-ST_min,Category-ST_max
0,0,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Artificial Intelligence and Machine Learning,Artificial Intelligence and Machine Learning [AI],"KR Circle, Bengaluru",Bengaluru,AI,10087,...,7188,7188,7791,7791,6935,8653,26148,33645,24190,33807
1,1,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Civil Engineering,Civil Engineering [CE],"KR Circle, Bengaluru",Bengaluru,CE,126281,...,79965,88750,93233,153643,74111,86716,105351,186680,109874,129504
2,2,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Computers Science And Engineering,Computers Science And Engineering [CS],"KR Circle, Bengaluru",Bengaluru,CS,5809,...,4749,5774,4889,5708,4344,6701,20990,29187,15475,20958
3,3,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Electronics and Communication Engineering,Electronics and Communication Engineering [EC],"KR Circle, Bengaluru",Bengaluru,EC,15177,...,10997,12440,10574,14664,9878,14864,33658,47113,37482,52570
4,4,E001,University of Visvesvaraya College of Engineer...,University of Visvesvaraya College of Engineer...,Electrical And Electronics Engineering,Electrical And Electronics Engineering [EE],"KR Circle, Bengaluru",Bengaluru,EE,41399,...,26321,26321,28487,34904,23821,32204,69595,74966,72997,78257
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,1464,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (CLOUD,B TECH IN COMPUTER SCIENCE (CLOUD [LF],Davanagere,Davanagere,LF,0,...,0,0,0,0,196309,196309,0,0,0,0
1465,1465,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (CYBER SECURITY),B TECH IN COMPUTER SCIENCE (CYBER SECURITY) [LG],Davanagere,Davanagere,LG,0,...,0,0,0,0,182360,182360,196735,196735,0,0
1466,1466,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (INFORMATION),B TECH IN COMPUTER SCIENCE (INFORMATION) [LH],Davanagere,Davanagere,LH,0,...,0,0,0,0,200270,200270,0,0,0,0
1467,1467,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYST...,BTECH IN COMPUTER SCIENCE & ENGG(BUSINESS SYST...,Davanagere,Davanagere,LJ,0,...,0,0,0,0,196205,196205,0,0,0,0
1468,1468,E303,"G M UNIVERSITY KARUR VILLAGE, DAVANGERE","G M UNIVERSITY KARUR VILLAGE, DAVANGERE [E303]",B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS),B TECH IN COMPUTER SCIENCE (INTERNET OF THINGS...,Davanagere,Davanagere,LK,0,...,0,0,0,0,178340,178340,0,0,0,0

In [222]:
result_df.drop(columns = ['Unnamed: 0'], inplace=True)

In [223]:
result_df.columns

Index(['InstituteId', 'InstituteName', 'Institution', 'CourseName', 'Course',
       'Location', 'City', 'BranchCode', '1G', '1K', '1R', '2AG', '2AK', '2AR',
       '2BG', '2BK', '2BR', '3AG', '3AK', '3AR', '3BG', '3BK', '3BR', 'GM',
       'GMK', 'GMR', 'SCG', 'SCK', 'SCR', 'STG', 'STK', 'STR', 'AvgCutoffRank',
       'Category-1_min', 'Category-1_max', 'Category-2A_min',
       'Category-2A_max', 'Category-2B_min', 'Category-2B_max',
       'Category-3A_min', 'Category-3A_max', 'Category-3B_min',
       'Category-3B_max', 'Category-GM_min', 'Category-GM_max',
       'Category-SC_min', 'Category-SC_max', 'Category-ST_min',
       'Category-ST_max'],
      dtype='object')

In [224]:
result_df.to_csv("dummy.csv")

In [230]:
result_df = result_df.sort_values(by='AvgCutoffRank')

In [231]:
result_df['AvgCutoffRank'].max()

np.int64(203368)

In [232]:
result_df

,InstituteId,InstituteName,Institution,CourseName,Course,Location,City,BranchCode,1G,1K,...,Category-3A_min,Category-3A_max,Category-3B_min,Category-3B_max,Category-GM_min,Category-GM_max,Category-SC_min,Category-SC_max,Category-ST_min,Category-ST_max
686,E112,Sri Krishna Institute of Technology Bangalore,Sri Krishna Institute of Technology Bangalore...,Civil Engineering,Civil Engineering [CE],"Chikkabanavara, Bengaluru",Bengaluru,CE,0,0,...,0,0,0,0,0,0,0,0,0,0
1029,E174,Dr. Sri. Sri. Sri. Shivakumara Mahaswamyji Col...,Dr. Sri. Sri. Sri. Shivakumara Mahaswamyji Col...,Civil Engineering,Civil Engineering [CE],"Kammasandra, Bengaluru Rural",Bengaluru Rural,CE,0,0,...,0,0,0,0,0,0,0,0,0,0
1034,E174,Dr. Sri. Sri. Sri. Shivakumara Mahaswamyji Col...,Dr. Sri. Sri. Sri. Shivakumara Mahaswamyji Col...,Mechanical Engineering,Mechanical Engineering [ME],"Kammasandra, Bengaluru Rural",Bengaluru Rural,ME,0,0,...,0,0,0,0,0,0,0,0,0,0
1037,E175,S.G.Balekundri Institute of Technology Belgaum,S.G.Balekundri Institute of Technology Belgau...,Civil Engineering,Civil Engineering [CE],Belgaum,Belgaum,CE,0,0,...,0,0,0,0,0,0,0,0,0,0
1366,E260,Nitte School of Architecture YELAHANKA BANGALORE,Nitte School of Architecture YELAHANKA BANGAL...,DESIGN,DESIGN [DG],"Yelahanka,Bengaluru",Bengaluru,DG,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1075,E184,C Byre Gowda Institute of Technology Kolar,C Byre Gowda Institute of Technology Kolar [E...,Computer Engineering,Computer Engineering [CO],Kolar,Kolar,CO,0,0,...,0,0,0,0,203287,203287,0,0,0,0
445,E075,Ballari Institute of Technology and Management...,Ballari Institute of Technology and Management...,Civil Engineering,Civil Engineering [CE],"Near Allipur, Bellary",Bellary,CE,0,0,...,0,0,0,0,203288,203288,0,0,0,0
1408,E281,"Government Engineering College Challakere,Chi...","Government Engineering College Challakere,Chi...",Automobile Engineering,Automobile Engineering [AU],Chitradurga,Chitradurga,AU,0,0,...,0,0,0,0,203325,203325,0,0,0,0
834,E139,Impact College of Engineering and Applied Scie...,Impact College of Engineering and Applied Scie...,Automation and Robotics Engineering,Automation and Robotics Engineering [RO],"Sahakara Nagar, Bengaluru",Bengaluru,RO,0,0,...,0,0,0,0,203331,203331,0,0,0,0
214,E031,Basaveshwara Engineering College Bagalkot,Basaveshwara Engineering College Bagalkot [E031],Mechanical Engineering,Mechanical Engineering [ME],"Vidayagiri, Bagalkot",Bagalkot,ME,0,0,...,0,0,0,0,203368,203368,0,0,0,0

In [233]:
result_df.to_csv(project_root / 'dataset' / 'dataset.csv')

In [235]:
result_df[result_df['AvgCutoffRank'] == 0].to_csv('dummy.csv')

In [236]:
result_df.columns

Index(['InstituteId', 'InstituteName', 'Institution', 'CourseName', 'Course',
       'Location', 'City', 'BranchCode', '1G', '1K', '1R', '2AG', '2AK', '2AR',
       '2BG', '2BK', '2BR', '3AG', '3AK', '3AR', '3BG', '3BK', '3BR', 'GM',
       'GMK', 'GMR', 'SCG', 'SCK', 'SCR', 'STG', 'STK', 'STR', 'AvgCutoffRank',
       'Category-1_min', 'Category-1_max', 'Category-2A_min',
       'Category-2A_max', 'Category-2B_min', 'Category-2B_max',
       'Category-3A_min', 'Category-3A_max', 'Category-3B_min',
       'Category-3B_max', 'Category-GM_min', 'Category-GM_max',
       'Category-SC_min', 'Category-SC_max', 'Category-ST_min',
       'Category-ST_max'],
      dtype='object')

In [237]:
result_df

,InstituteId,InstituteName,Institution,CourseName,Course,Location,City,BranchCode,1G,1K,...,Category-3A_min,Category-3A_max,Category-3B_min,Category-3B_max,Category-GM_min,Category-GM_max,Category-SC_min,Category-SC_max,Category-ST_min,Category-ST_max
686,E112,Sri Krishna Institute of Technology Bangalore,Sri Krishna Institute of Technology Bangalore...,Civil Engineering,Civil Engineering [CE],"Chikkabanavara, Bengaluru",Bengaluru,CE,0,0,...,0,0,0,0,0,0,0,0,0,0
1029,E174,Dr. Sri. Sri. Sri. Shivakumara Mahaswamyji Col...,Dr. Sri. Sri. Sri. Shivakumara Mahaswamyji Col...,Civil Engineering,Civil Engineering [CE],"Kammasandra, Bengaluru Rural",Bengaluru Rural,CE,0,0,...,0,0,0,0,0,0,0,0,0,0
1034,E174,Dr. Sri. Sri. Sri. Shivakumara Mahaswamyji Col...,Dr. Sri. Sri. Sri. Shivakumara Mahaswamyji Col...,Mechanical Engineering,Mechanical Engineering [ME],"Kammasandra, Bengaluru Rural",Bengaluru Rural,ME,0,0,...,0,0,0,0,0,0,0,0,0,0
1037,E175,S.G.Balekundri Institute of Technology Belgaum,S.G.Balekundri Institute of Technology Belgau...,Civil Engineering,Civil Engineering [CE],Belgaum,Belgaum,CE,0,0,...,0,0,0,0,0,0,0,0,0,0
1366,E260,Nitte School of Architecture YELAHANKA BANGALORE,Nitte School of Architecture YELAHANKA BANGAL...,DESIGN,DESIGN [DG],"Yelahanka,Bengaluru",Bengaluru,DG,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1075,E184,C Byre Gowda Institute of Technology Kolar,C Byre Gowda Institute of Technology Kolar [E...,Computer Engineering,Computer Engineering [CO],Kolar,Kolar,CO,0,0,...,0,0,0,0,203287,203287,0,0,0,0
445,E075,Ballari Institute of Technology and Management...,Ballari Institute of Technology and Management...,Civil Engineering,Civil Engineering [CE],"Near Allipur, Bellary",Bellary,CE,0,0,...,0,0,0,0,203288,203288,0,0,0,0
1408,E281,"Government Engineering College Challakere,Chi...","Government Engineering College Challakere,Chi...",Automobile Engineering,Automobile Engineering [AU],Chitradurga,Chitradurga,AU,0,0,...,0,0,0,0,203325,203325,0,0,0,0
834,E139,Impact College of Engineering and Applied Scie...,Impact College of Engineering and Applied Scie...,Automation and Robotics Engineering,Automation and Robotics Engineering [RO],"Sahakara Nagar, Bengaluru",Bengaluru,RO,0,0,...,0,0,0,0,203331,203331,0,0,0,0
214,E031,Basaveshwara Engineering College Bagalkot,Basaveshwara Engineering College Bagalkot [E031],Mechanical Engineering,Mechanical Engineering [ME],"Vidayagiri, Bagalkot",Bagalkot,ME,0,0,...,0,0,0,0,203368,203368,0,0,0,0

In [248]:
branch_df = result_df[ ['InstituteId', 'Institution', 'Course']]

In [250]:
branch_df = branch_df.sort_values(by = ['InstituteId', 'Course'])

In [254]:
branch_df.to_csv('branch.csv')

In [255]:
import pandas as pd
import json

# Load your CSV file
df = pd.read_csv('branch.csv')

# Create a dictionary to store the data in the desired format
institutions = {}

# Iterate through the DataFrame rows and populate the dictionary
for index, row in df.iterrows():
    institution = row['Institution'].strip()
    course = row['Course'].strip()
    
    if institution not in institutions:
        institutions[institution] = []
        
    institutions[institution].append(course)

# Save the dictionary as a JSON file
with open('institutions_courses.json', 'w') as json_file:
    json.dump(institutions, json_file, indent=4)

print("JSON file created successfully.")

JSON file created successfully.

In [257]:
result_df

,InstituteId,InstituteName,Institution,CourseName,Course,Location,City,BranchCode,1G,1K,...,Category-3A_min,Category-3A_max,Category-3B_min,Category-3B_max,Category-GM_min,Category-GM_max,Category-SC_min,Category-SC_max,Category-ST_min,Category-ST_max
686,E112,Sri Krishna Institute of Technology Bangalore,Sri Krishna Institute of Technology Bangalore...,Civil Engineering,Civil Engineering [CE],"Chikkabanavara, Bengaluru",Bengaluru,CE,0,0,...,0,0,0,0,0,0,0,0,0,0
1029,E174,Dr. Sri. Sri. Sri. Shivakumara Mahaswamyji Col...,Dr. Sri. Sri. Sri. Shivakumara Mahaswamyji Col...,Civil Engineering,Civil Engineering [CE],"Kammasandra, Bengaluru Rural",Bengaluru Rural,CE,0,0,...,0,0,0,0,0,0,0,0,0,0
1034,E174,Dr. Sri. Sri. Sri. Shivakumara Mahaswamyji Col...,Dr. Sri. Sri. Sri. Shivakumara Mahaswamyji Col...,Mechanical Engineering,Mechanical Engineering [ME],"Kammasandra, Bengaluru Rural",Bengaluru Rural,ME,0,0,...,0,0,0,0,0,0,0,0,0,0
1037,E175,S.G.Balekundri Institute of Technology Belgaum,S.G.Balekundri Institute of Technology Belgau...,Civil Engineering,Civil Engineering [CE],Belgaum,Belgaum,CE,0,0,...,0,0,0,0,0,0,0,0,0,0
1366,E260,Nitte School of Architecture YELAHANKA BANGALORE,Nitte School of Architecture YELAHANKA BANGAL...,DESIGN,DESIGN [DG],"Yelahanka,Bengaluru",Bengaluru,DG,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1075,E184,C Byre Gowda Institute of Technology Kolar,C Byre Gowda Institute of Technology Kolar [E...,Computer Engineering,Computer Engineering [CO],Kolar,Kolar,CO,0,0,...,0,0,0,0,203287,203287,0,0,0,0
445,E075,Ballari Institute of Technology and Management...,Ballari Institute of Technology and Management...,Civil Engineering,Civil Engineering [CE],"Near Allipur, Bellary",Bellary,CE,0,0,...,0,0,0,0,203288,203288,0,0,0,0
1408,E281,"Government Engineering College Challakere,Chi...","Government Engineering College Challakere,Chi...",Automobile Engineering,Automobile Engineering [AU],Chitradurga,Chitradurga,AU,0,0,...,0,0,0,0,203325,203325,0,0,0,0
834,E139,Impact College of Engineering and Applied Scie...,Impact College of Engineering and Applied Scie...,Automation and Robotics Engineering,Automation and Robotics Engineering [RO],"Sahakara Nagar, Bengaluru",Bengaluru,RO,0,0,...,0,0,0,0,203331,203331,0,0,0,0
214,E031,Basaveshwara Engineering College Bagalkot,Basaveshwara Engineering College Bagalkot [E031],Mechanical Engineering,Mechanical Engineering [ME],"Vidayagiri, Bagalkot",Bagalkot,ME,0,0,...,0,0,0,0,203368,203368,0,0,0,0

In [264]:
result_df.sort_values(by = ('AvgCutoffRank'))[result_df['AvgCutoffRank'] != 0].to_csv('option_entry.csv')

C:\Users\cheth\AppData\Local\Temp\ipykernel_2396\654475139.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  result_df.sort_values(by = ('AvgCutoffRank'))[result_df['AvgCutoffRank'] != 0].to_csv('option_entry.csv')

In [266]:
result_df.columns

Index(['InstituteId', 'InstituteName', 'Institution', 'CourseName', 'Course',
       'Location', 'City', 'BranchCode', '1G', '1K', '1R', '2AG', '2AK', '2AR',
       '2BG', '2BK', '2BR', '3AG', '3AK', '3AR', '3BG', '3BK', '3BR', 'GM',
       'GMK', 'GMR', 'SCG', 'SCK', 'SCR', 'STG', 'STK', 'STR', 'AvgCutoffRank',
       'Category-1_min', 'Category-1_max', 'Category-2A_min',
       'Category-2A_max', 'Category-2B_min', 'Category-2B_max',
       'Category-3A_min', 'Category-3A_max', 'Category-3B_min',
       'Category-3B_max', 'Category-GM_min', 'Category-GM_max',
       'Category-SC_min', 'Category-SC_max', 'Category-ST_min',
       'Category-ST_max'],
      dtype='object')